import typing

if typing.TYPE_CHECKING:
    from .__init__ import FFXWorld
else:
    FFXWorld = object

def setup_options_from_slot_data(world: FFXWorld) -> None:
    if hasattr(world.multiworld, "re_gen_passthrough"):
        if "Final Fantasy X" in world.multiworld.re_gen_passthrough:
            world.using_ut = True
            world.passthrough = world.multiworld.re_gen_passthrough["Final Fantasy X"]

            world.options.goal_requirement.value          = world.passthrough["goal_requirement"]
            world.options.required_party_members.value    = world.passthrough["required_party_members"]
            world.options.required_primers.value          = world.passthrough["required_primers"]
            world.options.sphere_grid_randomization.value = world.passthrough["sphere_grid_randomization"]
            world.options.mini_games.value                = world.passthrough["mini_games"]
            world.options.recruit_sanity.value            = world.passthrough["recruit_sanity"]
            world.options.capture_sanity.value            = world.passthrough["capture_sanity"]
            world.options.creation_rewards.value          = world.passthrough["creation_rewards"]
            world.options.arena_bosses.value              = world.passthrough["arena_bosses"]  
            world.options.super_bosses.value              = world.passthrough["super_bosses"]
            world.options.always_capture.value            = world.passthrough["always_capture"]
            world.options.logic_difficulty.value          = world.passthrough["logic_difficulty"]
            
            

        else:
            world.using_ut = False
    else:
        world.using_ut = False

room_to_map = {
    23  : "Spira",
    382 : "Spira",
    48  : "Baaj Temple",
    49  : "Baaj Temple",
    50  : "Baaj Temple",
    63  : "Baaj Temple",
    52  : "Baaj Temple",
    74  : "Baaj Temple",
    295 : "Baaj Temple",
    196 : "Baaj Temple",
    298 : "Baaj Temple",
    51  : "Baaj Temple",
    71  : "Al Bhed Ship",
    288 : "Al Bhed Ship",
    64  : "Al Bhed Ship",
    380 : "Al Bhed Ship",
    70  : "Besaid Island",
    20  : "Besaid Island",
    41  : "Besaid Island",
    67  : "Besaid Island",
    69  : "Besaid Island",
    133 : "Besaid Village",
    17  : "Besaid Village",
    142 : "Besaid Village",
    144 : "Besaid Village",
    145 : "Besaid Village",
    60  : "Besaid Village",
    143 : "Besaid Village",
    84  : "Besaid Village",
    42  : "Besaid Temple",
    147 : "Besaid Temple",
    146 : "Besaid Temple",
    122 : "Besaid Temple",
    103 : "Besaid Temple",
    83  : "Besaid Village",
    100 : "Besaid Village",
    252 : "Besaid Village",
    68  : "Besaid Village",
    117 : "Besaid Village",
    21  : "Besaid Island",
    22  : "Besaid Island",
    19  : "Besaid Island",
    301 : "S.S. Liki",
    148 : "S.S. Liki",
    149 : "S.S. Liki",
    150 : "S.S. Liki",
    154 : "S.S. Liki",
    61  : "S.S. Liki",
    282 : "S.S. Liki",
    220 : "S.S. Liki",
    139 : "S.S. Liki",
    43  : "Kilika Village",
    53  : "Kilika Village",
    152 : "Kilika Village",
    46  : "Kilika Village",
    16  : "Kilika Village",
    151 : "Kilika Village",
    293 : "Kilika Village",
    98  : "Kilika Village",
    47  : "Kilika Village",
    166 : "Kilika Village",
    294 : "Kilika Village",
    18  : "Kilika Village",
    65  : "Kilika Village",
    78  : "Kilika Temple",
    155 : "Kilika Temple",
    156 : "Kilika Temple",
    96  : "Kilika Temple",
    44  : "Kilika Temple",
    108 : "Kilika Temple",
    45  : "Kilika Temple",
    297 : "Kilika Temple",
    118 : "Kilika Temple",
    94  : "S.S. Winno",
    167 : "S.S. Winno",
    237 : "S.S. Winno",
    168 : "S.S. Winno",
    169 : "S.S. Winno",
    191 : "S.S. Winno",
    185 : "S.S. Winno",
    302 : "S.S. Winno",
    267 : "Luca",
    377 : "Luca",
    268 : "Luca",
    355 : "Luca",
    72  : "Luca",
    123 : "Luca",
    73  : "Luca",
    85  : "Luca",
    86  : "Luca",
    87  : "Luca",
    88  : "Luca",
    89  : "Luca",
    77  : "Luca",
    157 : "Luca",
    170 : "Luca",
    158 : "Luca",
    184 : "Luca",
    104 : "Luca",
    107 : "Luca",
    121 : "Luca",
    159 : "Luca",
    299 : "Luca",
    113 : "Luca",
    124 : "Luca",
    62  : "Luca",
    212 : "Luca",
    347 : "Luca",
    250 : "Luca",
    125 : "Luca",
    57  : "Luca",
    55  : "Luca",
    95  : "Miihen Highroad",
    120 : "Miihen Highroad",
    127 : "Miihen Highroad",
    58  : "Miihen Highroad",
    171 : "Miihen Highroad",
    112 : "Miihen Highroad",
    115 : "Miihen Highroad",
    116 : "Miihen Highroad",
    59  : "Miihen Highroad",
    79  : "Mushroom Rock Road",
    92  : "Mushroom Rock Road",
    128 : "Mushroom Rock Road",
    119 : "Mushroom Rock Road",
    247 : "Mushroom Rock Road",
    254 : "Mushroom Rock Road",
    218 : "Mushroom Rock Road",
    341 : "Mushroom Rock Road",
    289 : "Mushroom Rock Road",
    131 : "Mushroom Rock Road",
    93  : "Djose",
    76  : "Djose",
    82  : "Djose",
    210 : "Djose",
    81  : "Djose",
    161 : "Djose",
    160 : "Djose",
    214 : "Djose",
    90  : "Djose",
    91  : "Djose",
    245 : "Djose",
    75  : "Moonflow",
    105 : "Moonflow",
    187 : "Moonflow",
    188 : "Moonflow",
    234 : "Moonflow",
    235 : "Moonflow",
    99  : "Moonflow",
    291 : "Moonflow",
    236 : "Moonflow",
    190 : "Moonflow",
    189 : "Moonflow",
    109 : "Moonflow",
    97  : "Moonflow",
    135 : "Guadosalam",
    243 : "Guadosalam",
    174 : "Guadosalam",
    173 : "Guadosalam",
    172 : "Guadosalam",
    163 : "Guadosalam",
    141 : "Guadosalam",
    197 : "Guadosalam",
    217 : "Guadosalam",
    175 : "Guadosalam",
    257 : "Guadosalam",
    193 : "Guadosalam",
    364 : "Guadosalam",
    213 : "Guadosalam",
    134 : "Guadosalam",
    140 : "Thunder Plains",
    256 : "Thunder Plains",
    263 : "Thunder Plains",
    264 : "Thunder Plains",
    262 : "Thunder Plains",
    162 : "Thunder Plains",
    110 : "Macalania Woods",
    241 : "Macalania Woods",
    242 : "Macalania Woods",
    221 : "Macalania Woods",
    248 : "Macalania Woods",
    330 : "Macalania Woods",
    331 : "Macalania Woods",
    391 : "Macalania Woods",
    164 : "Lake Macalania",
    215 : "Lake Macalania",
    102 : "Lake Macalania",
    192 : "Lake Macalania",
    153 : "Lake Macalania",
    106 : "Macalania Temple",
    178 : "Macalania Temple",
    179 : "Macalania Temple",
    239 : "Macalania Temple",
    80  : "Macalania Temple",
    284 : "Macalania Temple",
    365 : "Lake Macalania",
    54  : "Lake Macalania",
    260 : "Lake Macalania",
    129 : "Bikanel",
    136 : "Bikanel",
    137 : "Bikanel",
    138 : "Bikanel",
    130 : "Home",
    276 : "Home",
    280 : "Home",
    286 : "Home",
    275 : "Home",
    219 : "Home",
    303 : "Home",
    261 : "Home",
    194 : "Airship",
    265 : "Airship",
    351 : "Airship",
    211 : "Airship",
    277 : "Airship",
    255 : "Airship",
    392 : "Airship",
    199 : "Airship",
    200 : "Airship",
    201 : "Airship",
    374 : "Airship",
    375 : "Airship",
    202 : "Airship",
    205 : "Bevelle",
    180 : "Bevelle",
    181 : "Bevelle",
    182 : "Bevelle",
    306 : "Bevelle",
    226 : "Bevelle",
    198 : "Via Purifico",
    209 : "Via Purifico",
    208 : "Via Purifico",
    183 : "Via Purifico",
    274 : "Via Purifico",
    206 : "Via Purifico",
    177 : "Via Purifico",
    176 : "Via Purifico",
    329 : "Via Purifico",
    238 : "Via Purifico",
    227 : "Bevelle",
    195 : "Bevelle",
    207 : "Bevelle",
    269 : "Bevelle",
    273 : "Bevelle",
    287 : "Bevelle",
    305 : "Bevelle",
    223 : "Plains",
    290 : "Remiem Temple",
    308 : "Remiem Temple",
    372 : "Remiem Temple",
    307 : "Monster Arena",
    279 : "Calm Lands",
    266 : "Calm Lands",
    56  : "Cavern of the Stolen Fayth",
    283 : "Cavern of the Stolen Fayth",
    259 : "Gagazet Outside",
    244 : "Gagazet Outside",
    285 : "Gagazet Outside",
    309 : "Gagazet Outside",
    165 : "Gagazet Outside",
    249 : "Gagazet Outside",
    272 : "Gagazet Cave",
    310 : "Gagazet Cave",
    311 : "Gagazet Cave",
    312 : "Gagazet Cave",
    361 : "Gagazet Cave",
    362 : "Gagazet Cave",
    381 : "Gagazet Cave",
    383 : "Gagazet Cave",
    132 : "Zanarkand Ruins",
    363 : "Zanarkand Ruins",
    225 : "Zanarkand Ruins",
    314 : "Zanarkand Ruins",
    222 : "Zanarkand Ruins",
    316 : "Zanarkand Ruins",
    313 : "Zanarkand Ruins",
    320 : "Zanarkand Temple",
    317 : "Zanarkand Temple",
    318 : "Zanarkand Temple",
    224 : "Zanarkand Temple",
    270 : "Zanarkand Temple",
    319 : "Zanarkand Temple",
    315 : "Zanarkand Ruins",
    322 : "Inside Sin",
    203 : "Inside Sin",
    296 : "Inside Sin",
    204 : "Inside Sin",
    327 : "Inside Sin",
    324 : "Inside Sin",
    325 : "Inside Sin",
    326 : "Inside Sin",
    258 : "Omega Ruins",
    271 : "Omega Ruins",
}

map_to_index = {
    "Airship": 0,
    "Al Bhed Ship": 1,
    "Baaj Temple": 2,
    "Besaid Island": 3,
    "Besaid Temple": 4,
    "Besaid Village": 5,
    "Bevelle": 6,
    "Bikanel": 7,
    "Calm Lands": 8,
    "Cavern of the Stolen Fayth": 9,
    "Djose": 10,
    "Gagazet Outside": 11,
    "Gagazet Cave": 12,
    "Guadosalam": 13,
    "Home": 14,
    "Inside Sin": 15,
    "Kilika Temple": 16,
    "Kilika Village": 17,
    "Lake Macalania": 18,
    "Luca": 19,
    "Macalania Temple": 20,
    "Macalania Woods": 21,
    "Miihen Highroad": 22,
    "Monster Arena": 23,
    "Monster Arena - Besaid": 24,
    "Monster Arena - Kilika": 25,
    "Monster Arena - Miihen Highroad": 26,
    "Monster Arena - Mushroom Rock Road": 27,
    "Monster Arena - Djose Road": 28,
    "Monster Arena - Thunder Plains": 29,
    "Monster Arena - Macalania": 30,
    "Monster Arena - Bikanel": 31,
    "Monster Arena - Calm Lands": 32,
    "Monster Arena - Cavern of the Stolen Fayth": 33,
    "Monster Arena - Mt. Gagazet": 34,
    "Monster Arena - Inside Sin": 35,
    "Monster Arena - Omega Ruins": 36,
    "Monster Arena - Area Conquest": 37,
    "Monster Arena - Species Conquest": 38,
    "Monster Arena - Original Creation": 39,
    "Moonflow": 40,
    "Mushroom Rock Road": 41,
    "Omega Ruins": 42,
    "Remiem Temple": 43,
    "S.S. Liki": 44,
    "S.S. Winno": 45,
    "Sin": 46,
    "Spira": 47,
    "Thunder Plains": 48,
    "Via Purifico": 49,
    "Zanarkand Ruins": 50,
    "Zanarkand Temple": 51
}

def map_page_index(data) -> int:
    map_name = room_to_map.get(data, "Spira")
    return map_to_index.get(map_name, 47)


poptracker_name_mapping = {
    "Al Bhed Primers/Complete Al Bhed Primers": 4501,
    "Al Bhed Primer I/Al Bhed Ship": 24577,
    "Al Bhed Primer I/Bikanel": 24577,
    "Al Bhed Primer II/Besaid": 24578,
    "Al Bhed Primer III/S.S. Liki": 24579,
    "Al Bhed Primer III/Bikanel": 24579,
    "Al Bhed Primer IV/Kilika": 24580,
    "Al Bhed Primer V/S.S. Winno": 24581,
    "Al Bhed Primer V/Bikanel": 24581,
    "Al Bhed Primer VI/Luca": 24582,
    "Al Bhed Primer VII/Luca": 24583,
    "Al Bhed Primer VIII/Miihen Highroad": 24584,
    "Al Bhed Primer IX/Miihen Highroad": 24585,
    "Al Bhed Primer X/Mushroom Rock Road": 24586,
    "Al Bhed Primer XI/Djose": 24587,
    "Al Bhed Primer XII/Moonflow": 24588,
    "Al Bhed Primer XIII/Guadosalam": 24589,
    "Al Bhed Primer XIV/Thunder Plains": 24590,
    "Al Bhed Primer XIV/Bikanel": 24590,
    "Al Bhed Primer XV/Macalania": 24591,
    "Al Bhed Primer XVI/Macalania": 24592,
    "Al Bhed Primer XVII/Bikanel": 24593,
    "Al Bhed Primer XVIII/Bikanel": 24594,
    "Al Bhed Primer XIX/Home": 24595,
    "Al Bhed Primer XX/Home": 24596,
    "Al Bhed Primer XXI/Home": 24597,
    "Al Bhed Primer XXII/Bevelle": 24598,
    "Al Bhed Primer XXIII/Calm Lands": 24599,
    "Al Bhed Primer XXIV/Remiem Temple": 24600,
    "Al Bhed Primer XXV/Cavern of the Stolen Fayth": 24601,
    "Al Bhed Primer XXVI/Omega Ruins": 24602,
    "Blitzball Recruits/Biggs": 28673,
    "Blitzball Recruits/Brother": 28674,
    "Blitzball Recruits/Durren": 28675,
    "Blitzball Recruits/Jumal": 28676,
    "Blitzball Recruits/Kiyuri": 28677,
    "Blitzball Recruits/Kyou": 28678,
    "Blitzball Recruits/Linna": 28679,
    "Blitzball Recruits/Mep": 28680,
    "Blitzball Recruits/Mifurey": 28681,
    "Blitzball Recruits/Miyu": 28682,
    "Blitzball Recruits/Naida": 28683,
    "Blitzball Recruits/Nedus": 28684,
    "Blitzball Recruits/Rin": 28685,
    "Blitzball Recruits/Ropp": 28686,
    "Blitzball Recruits/Shaami": 28687,
    "Blitzball Recruits/Shuu": 28688,
    "Blitzball Recruits/Svanda": 28689,
    "Blitzball Recruits/Tatts": 28690,
    "Blitzball Recruits/Vilucha": 28691,
    "Blitzball Recruits/Wakka": 28692,
    "Blitzball Recruits/Wedge": 28693,
    "Blitzball Recruits/Yuma Guado": 28694,
    "Blitzball Recruits/Zalitz": 28695,
    "Blitzball Recruits/Zev Ronso": 28696,
    "Auron/Masamune": 4195,
    "Auron/Mars Crest": 4365,
    "Auron/Mars Sigil": 4372,
    "Auron/Masamune Crest Upgrade": 24618,
    "Auron/Masamune Sigil Upgrade": 24619,
    "Kimahri/Spirit Lance": 4284,
    "Kimahri/Saturn Crest": 4366,
    "Kimahri/Saturn Sigil": 4373,
    "Kimahri/Spirit Lance Crest Upgrade": 24620,
    "Kimahri/Spirit Lance Sigil Upgrade": 24621,
    "Lulu/Onion Knight": 4101,
    "Lulu/Venus Crest": 4368,
    "Lulu/Venus Sigil": 4374,
    "Lulu/Onion Knight Crest Upgrade": 24624,
    "Lulu/Onion Knight Sigil Upgrade": 24625,
    "Rikku/Godhand": 4310,
    "Rikku/Mercury Crest": 4369,
    "Rikku/Mercury Sigil": 4375,
    "Rikku/Godhand Crest Upgrade": 24626,
    "Rikku/Godhand Sigil Upgrade": 24627,
    "Tidus/Caladbolg": 4210,
    "Tidus/Sun Crest": 4363,
    "Tidus/Sun Sigil": 4370,
    "Tidus/Brotherhood": 4304,
    "Tidus/Brotherhood Upgrade": 24613,
    "Tidus/Caladbolg Crest Upgrade": 24614,
    "Tidus/Caladbolg Sigil Upgrade": 24615,
    "Wakka/World Champion": 4189,
    "Wakka/Jupiter Crest": 4367,
    "Wakka/Jupiter Sigil": 4340,
    "Wakka/World Champion Crest Upgrade": 24622,
    "Wakka/World Champion Sigil Upgrade": 24623,
    "Yuna/Nirvana": 4209,
    "Yuna/Moon Crest": 4364,
    "Yuna/Moon Sigil": 4371,
    "Yuna/Nirvana Crest Upgrade": 24616,
    "Yuna/Nirvana Sigil Upgrade": 24617,
    "General/Cloudy Mirror": 4272,
    "General/Celestial Mirror": 4207,
    "General/Rusty Sword": 4214,
    "Aeon/Anima": 12301,
    "Aeon/Bahamut": 12300,
    "Aeon/Ifrit": 12297,
    "Aeon/Ixion": 12298,
    "Aeon/Magus Sisters": 12303,
    "Aeon/Shiva": 12299,
    "Aeon/Valefor": 12296,
    "Aeon/Yojimbo": 12302,
    "Character/Auron": 12290,
    "Character/Kimahri": 12291,
    "Character/Lulu": 12293,
    "Character/Rikku": 12294,
    "Character/Seymour": 12295,
    "Character/Tidus": 12288,
    "Character/Wakka": 12292,
    "Character/Yuna": 12289,
    "Super Bosses/Omega Weapon": 8236,
    "Super Bosses/Dark Anima": 8226,
    "Super Bosses/Dark Bahamut": 8230,
    "Super Bosses/Dark Cindy": 8239,
    "Super Bosses/Dark Ifrit": 8211,
    "Super Bosses/Dark Ixion": 8205,
    "Super Bosses/Dark Mindy": 8237,
    "Super Bosses/Dark Sandy": 8238,
    "Super Bosses/Dark Shiva": 8210,
    "Super Bosses/Dark Valefor": 8194,
    "Super Bosses/Dark Yojimbo": 8223,
    "Super Bosses/Penance": 8217,
    "Stratoavis/Defeated": 8241,
    "1 of Each Capture Required/Dingo": 36872,
    "1 of Each Capture Required/Condor": 36891,
    "1 of Each Capture Required/Water Flan": 36879,
    "Malboro Menace/Defeated": 8242,
    "1 of Each Capture Required/Dinonix": 36885,
    "1 of Each Capture Required/Killer Bee": 36894,
    "1 of Each Capture Required/Yellow Element": 36925,
    "1 of Each Capture Required/Ragora": 36902,
    "Kottos/Defeated": 8243,
    "1 of Each Capture Required/Miihen Fang": 36873,
    "1 of Each Capture Required/Ipiria": 36886,
    "1 of Each Capture Required/Floating Eye": 36886,
    "1 of Each Capture Required/White Element": 36926,
    "1 of Each Capture Required/Raldo": 36864,
    "1 of Each Capture Required/Vouivre": 36914,
    "1 of Each Capture Required/Bomb": 36949,
    "1 of Each Capture Required/Dual Horn": 36911,
    "Coeurlregina/Defeated": 8244,
    "1 of Each Capture Required/Raptor": 36887,
    "1 of Each Capture Required/Gandarewa": 36869,
    "1 of Each Capture Required/Thunder Flan": 36880,
    "1 of Each Capture Required/Red Element": 36927,
    "1 of Each Capture Required/Lamashtu": 36915,
    "1 of Each Capture Required/Funguar": 36915,
    "1 of Each Capture Required/Garuda": 36904,
    "Jormungand/Defeated": 8245,
    "1 of Each Capture Required/Garm": 36874,
    "1 of Each Capture Required/Simurgh": 36892,
    "1 of Each Capture Required/Bite Bug": 36895,
    "1 of Each Capture Required/Snow Flan": 36881,
    "1 of Each Capture Required/Bunyip": 36865,
    "1 of Each Capture Required/Basilisk": 36943,
    "1 of Each Capture Required/Ochu": 36947,
    "Cactuar King/Defeated": 8246,
    "1 of Each Capture Required/Melusine": 36888,
    "1 of Each Capture Required/Aerouge": 36870,
    "1 of Each Capture Required/Buer": 36899,
    "1 of Each Capture Required/Gold Element": 36928,
    "1 of Each Capture Required/Kusariqqu": 36916,
    "1 of Each Capture Required/Larva": 36953,
    "1 of Each Capture Required/Iron Giant": 36940,
    "1 of Each Capture Required/Qactuar": 36951,
    "Espada/Defeated": 8247,
    "1 of Each Capture Required/Snow Wolf": 36875,
    "1 of Each Capture Required/Iguion": 36889,
    "1 of Each Capture Required/Wasp": 36896,
    "1 of Each Capture Required/Evil Eye": 36900,
    "1 of Each Capture Required/Ice Flan": 36882,
    "1 of Each Capture Required/Blue Element": 36929,
    "1 of Each Capture Required/Murussu": 36866,
    "1 of Each Capture Required/Mafdet": 36867,
    "1 of Each Capture Required/Xiphos": 36958,
    "1 of Each Capture Required/Chimera": 36935,
    "Abyss Worm/Defeated": 8248,
    "1 of Each Capture Required/Sand Wolf": 36876,
    "1 of Each Capture Required/Alcyone": 36893,
    "1 of Each Capture Required/Mushussu": 36917,
    "1 of Each Capture Required/Zu": 36905,
    "1 of Each Capture Required/Sand Worm": 36906,
    "1 of Each Capture Required/Cactuar": 36952,
    "Chimerageist/Defeated": 8249,
    "1 of Each Capture Required/Skoll": 36877,
    "1 of Each Capture Required/Nebiros": 36897,
    "1 of Each Capture Required/Flame Flan": 36883,
    "1 of Each Capture Required/Shred": 36868,
    "1 of Each Capture Required/Anacondaur": 36944,
    "1 of Each Capture Required/Ogre": 36921,
    "1 of Each Capture Required/Coeurl": 36937,
    "1 of Each Capture Required/Chimera Brain": 36936,
    "1 of Each Capture Required/Malboro": 36919,
    "Don Tonberry/Defeated": 8250,
    "1 of Each Capture Required/Yowie": 36890,
    "1 of Each Capture Required/Imp": 36871,
    "1 of Each Capture Required/Dark Element": 36930,
    "1 of Each Capture Required/Nidhogg": 36918,
    "1 of Each Capture Required/Thorn": 36956,
    "1 of Each Capture Required/Valaha": 36912,
    "1 of Each Capture Required/Epaaj": 36932,
    "1 of Each Capture Required/Ghost": 36908,
    "1 of Each Capture Required/Tonberry": 36962,
    "Catoblepas/Defeated": 8251,
    "1 of Each Capture Required/Bandersnatch": 36878,
    "1 of Each Capture Required/Ahriman": 36901,
    "1 of Each Capture Required/Dark Flan": 36884,
    "1 of Each Capture Required/Grenade": 36950,
    "1 of Each Capture Required/Grat": 36903,
    "1 of Each Capture Required/Grendel": 36913,
    "1 of Each Capture Required/Bashura": 36922,
    "1 of Each Capture Required/Mandragora": 36948,
    "1 of Each Capture Required/Behemoth": 36933,
    "1 of Each Capture Required/Splasher": 36924,
    "1 of Each Capture Required/Achelous": 36909,
    "1 of Each Capture Required/Maelspike": 36910,
    "Abaddon/Defeated": 8252,
    "1 of Each Capture Required/Exoray": 36957,
    "1 of Each Capture Required/Wraith": 36961,
    "1 of Each Capture Required/Gemini (Sword)": 36941,
    "1 of Each Capture Required/Gemini (Club)": 36942,
    "1 of Each Capture Required/Demonolith": 36939,
    "1 of Each Capture Required/Great Malboro": 36920,
    "1 of Each Capture Required/Barbatos": 36954,
    "1 of Each Capture Required/Adamantoise": 36945,
    "1 of Each Capture Required/Behemoth King": 36934,
    "Vorban/Defeated": 8253,
    "1 of Each Capture Required/Zaurus": 36964,
    "1 of Each Capture Required/Floating Death": 36966,
    "1 of Each Capture Required/Black Element": 36931,
    "1 of Each Capture Required/Halma": 36965,
    "1 of Each Capture Required/Puroboros": 36959,
    "1 of Each Capture Required/Spirit": 36960,
    "1 of Each Capture Required/Machea": 36967,
    "1 of Each Capture Required/Master Coeurl": 36938,
    "1 of Each Capture Required/Master Tonberry": 36963,
    "1 of Each Capture Required/Varuna": 36946,
    "Dingo (3x Wolf)/Captured": 36872,
    "Condor (5x Bird)/Captured": 36891,
    "Water Flan (3x Flan)/Captured": 36879,
    "Sand Wolf (3x Wolf)/Captured": 36876,
    "Alcyone (5x Bird)/Captured": 36893,
    "Mushussu (5x Drake)/Captured": 36917,
    "Zu/Captured": 36905,
    "Sand Worm/Captured": 36906,
    "Cactuar/Captured": 36952,
    "Skoll (3x Wolf)/Captured": 36877,
    "Nebiros (4x Wasp)/Captured": 36897,
    "Flame Flan (3x Flan)/Captured": 36883,
    "Shred (3x Helm)/Captured": 36868,
    "Anacondaur/Captured": 36944,
    "Ogre/Captured": 36921,
    "Coeurl/Captured": 36937,
    "Chimera Brain/Captured": 36936,
    "Malboro/Captured": 36919,
    "Yowie (3x Reptile)/Captured": 36890,
    "Imp (Imp x4)/Captured": 36871,
    "Dark Element (3x Elemental)/Captured": 36930,
    "Nidhogg (5x Drake)/Captured": 36918,
    "Thorn (5x Fungus)/Captured": 36956,
    "Valaha (5x Ruminant)/Captured": 36912,
    "Epaaj/Captured": 36932,
    "Ghost/Captured": 36908,
    "Tonberry/Captured": 36962,
    "Garm (3x Wolf)/Captured": 36874,
    "Simurgh (5x Bird)/Captured": 36892,
    "Bite Bug (4x Hornet)/Captured": 36895,
    "Snow Flan (3x Flan)/Captured": 36881,
    "Bunyip (3x Helm)/Captured": 36865,
    "Basilisk/Captured": 36943,
    "Ochu/Captured": 36947,
    "Exoray (5x Fungus)/Captured": 36957,
    "Wraith/Captured": 36961,
    "Gemini (Sword) (10x Iron Giant)/Captured": 36941,
    "Gemini (Club) (10x Iron Giant)/Captured": 36942,
    "Demonolith/Captured": 36939,
    "Great Malboro/Captured": 36920,
    "Barbatos/Captured": 36954,
    "Adamantoise/Captured": 36945,
    "Behemoth King/Captured": 36934,
    "Dinonix (3x Reptile)/Captured": 36885,
    "Killer Bee (5x Wasp)/Captured": 36894,
    "Yellow Element (3x Elemental)/Captured": 36925,
    "Ragora/Captured": 36902,
    "Snow Wolf (3x Wolf)/Captured": 36875,
    "Iguion (3x Reptile)/Captured": 36889,
    "Wasp (4x Wasp)/Captured": 36896,
    "Evil Eye (4x Eye)/Captured": 36900,
    "Ice Flan (3x Flan)/Captured": 36882,
    "Blue Element (3x Elemental)/Captured": 36929,
    "Murussu (3x Helm)/Captured": 36866,
    "Mafdet (3x Helm)/Captured": 36867,
    "Xiphos/Captured": 36958,
    "Chimera/Captured": 36935,
    "Miihen Fang (3x Wolf)/Captured": 36873,
    "Ipiria (3x Reptile)/Captured": 36886,
    "Floating Eye (4x Eye)/Captured": 36886,
    "White Element (3x Elemental)/Captured": 36926,
    "Raldo (3x Armoured)/Captured": 36864,
    "Vouivre (5x Drake)/Captured": 36914,
    "Bomb (5x Bomb)/Captured": 36949,
    "Dual Horn (5x Ruminant)/Captured": 36911,
    "Fiends/Dingo (3x Wolf)": 36872,
    "Fiends/Condor (5x Bird)": 36891,
    "Fiends/Water Flan (3x Flan)": 36879,
    "Fiends/Dinonix (3x Reptile)": 36885,
    "Fiends/Killer Bee (5x Wasp)": 36894,
    "Fiends/Yellow Element (3x Elemental)": 36925,
    "Fiends/Ragora": 36902,
    "Fiends/Miihen Fang (3x Wolf)": 36873,
    "Fiends/Ipiria (3x Reptile)": 36886,
    "Fiends/Floating Eye (4x Eye)": 36886,
    "Fiends/White Element (3x Elemental)": 36926,
    "Fiends/Raldo (3x Armoured)": 36864,
    "Fiends/Vouivre (5x Drake)": 36914,
    "Fiends/Bomb (5x Bomb)": 36949,
    "Fiends/Dual Horn (5x Ruminant)": 36911,
    "Fiends/Raptor (3x Reptile)": 36887,
    "Fiends/Gandarewa (5x Imp)": 36869,
    "Fiends/Thunder Flan (3x Flan)": 36880,
    "Fiends/Red Element (3x Elemental)": 36927,
    "Fiends/Lamashtu (5x Drake)": 36915,
    "Fiends/Funguar (5x Fungus)": 36915,
    "Fiends/Garuda": 36904,
    "Fiends/Garm (3x Wolf)": 36874,
    "Fiends/Simurgh (5x Bird)": 36892,
    "Fiends/Bite Bug (4x Hornet)": 36895,
    "Fiends/Snow Flan (3x Flan)": 36881,
    "Fiends/Bunyip (3x Helm)": 36865,
    "Fiends/Basilisk": 36943,
    "Fiends/Ochu": 36947,
    "Fiends/Melusine (3x Reptile)": 36888,
    "Fiends/Aerouge (4x Imp)": 36870,
    "Fiends/Buer (4x Eye)": 36899,
    "Fiends/Gold Element (3x Elemental)": 36928,
    "Fiends/Kusariqqu (5x Drake)": 36916,
    "Fiends/Larva": 36953,
    "Fiends/Iron Giant (10x Iron Clad)": 36940,
    "Fiends/Qactuar": 36951,
    "Fiends/Snow Wolf (3x Wolf)": 36875,
    "Fiends/Iguion (3x Reptile)": 36889,
    "Fiends/Wasp (4x Wasp)": 36896,
    "Fiends/Evil Eye (4x Eye)": 36900,
    "Fiends/Ice Flan (3x Flan)": 36882,
    "Fiends/Blue Element (3x Elemental)": 36929,
    "Fiends/Murussu (3x Helm)": 36866,
    "Fiends/Mafdet (3x Helm)": 36867,
    "Fiends/Xiphos": 36958,
    "Fiends/Chimera": 36935,
    "Fiends/Sand Wolf (3x Wolf)": 36876,
    "Fiends/Alcyone (5x Bird)": 36893,
    "Fiends/Mushussu (5x Drake)": 36917,
    "Fiends/Zu": 36905,
    "Fiends/Sand Worm": 36906,
    "Fiends/Cactuar": 36952,
    "Fiends/Skoll (3x Wolf)": 36877,
    "Fiends/Nebiros (4x Wasp)": 36897,
    "Fiends/Flame Flan (3x Flan)": 36883,
    "Fiends/Shred (3x Helm)": 36868,
    "Fiends/Anacondaur": 36944,
    "Fiends/Ogre": 36921,
    "Fiends/Coeurl": 36937,
    "Fiends/Chimera Brain": 36936,
    "Fiends/Malboro": 36919,
    "Fiends/Yowie (3x Reptile)": 36890,
    "Fiends/Imp (Imp x4)": 36871,
    "Fiends/Dark Element (3x Elemental)": 36930,
    "Fiends/Nidhogg (5x Drake)": 36918,
    "Fiends/Thorn (5x Fungus)": 36956,
    "Fiends/Valaha (5x Ruminant)": 36912,
    "Fiends/Epaaj": 36932,
    "Fiends/Ghost": 36908,
    "Fiends/Tonberry": 36962,
    "Fiends/Bandersnatch (3x Wolf)": 36878,
    "Fiends/Ahriman (4x Eye)": 36901,
    "Fiends/Dark Flan (3x Flan)": 36884,
    "Fiends/Grenade (5x Bomb)": 36950,
    "Fiends/Grat": 36903,
    "Fiends/Grendel (5x Ruminant)": 36913,
    "Fiends/Bashura": 36922,
    "Fiends/Mandragora": 36948,
    "Fiends/Behemoth": 36933,
    "Fiends/Splasher (2x Shinryu)": 36924,
    "Fiends/Achelous (2x Shinryu)": 36909,
    "Fiends/Maelspike (2x Shinryu)": 36910,
    "Fiends/Exoray (5x Fungus)": 36957,
    "Fiends/Wraith": 36961,
    "Fiends/Gemini (Sword) (10x Iron Giant)": 36941,
    "Fiends/Gemini (Club) (10x Iron Giant)": 36942,
    "Fiends/Demonolith": 36939,
    "Fiends/Great Malboro": 36920,
    "Fiends/Barbatos": 36954,
    "Fiends/Adamantoise": 36945,
    "Fiends/Behemoth King": 36934,
    "Fiends/Zaurus (3x Reptile)": 36964,
    "Fiends/Floating Death (4x Eye)": 36966,
    "Fiends/Black Element (3x Elemental)": 36931,
    "Fiends/Halma (3x Helm)": 36965,
    "Fiends/Puroboros (5x Bomb)": 36959,
    "Fiends/Spirit": 36960,
    "Fiends/Machea": 36967,
    "Fiends/Master Coeurl": 36938,
    "Fiends/Master Tonberry": 36963,
    "Fiends/Varuna": 36946,
    "Creation Rewards/Besaid": 4520,
    "Creation Rewards/Kilika": 4521,
    "Creation Rewards/Miihen Highroad": 4522,
    "Creation Rewards/Mushroom Rock Road": 4523,
    "Creation Rewards/Djose Road": 4524,
    "Creation Rewards/Thunder Plains": 4525,
    "Creation Rewards/Macalania": 4526,
    "Creation Rewards/Bikanel": 4527,
    "Creation Rewards/Calm Lands": 4528,
    "Creation Rewards/Stolen Fayth Cavern": 4529,
    "Creation Rewards/Mt. Gagazet": 4530,
    "Creation Rewards/Inside Sin": 4531,
    "Creation Rewards/Omega Dungeon": 4532,
    "Defeat/Stratoavis": 8241,
    "Defeat/Malboro Menace": 8242,
    "Defeat/Kottos": 8243,
    "Defeat/Coeurlregina": 8244,
    "Defeat/Jormungand": 8245,
    "Defeat/Cactuar King": 8246,
    "Defeat/Espada": 8247,
    "Defeat/Abyss Worm": 8248,
    "Defeat/Chimerageist": 8249,
    "Defeat/Don Tonberry": 8250,
    "Defeat/Catoblepas": 8251,
    "Defeat/Abaddon": 8252,
    "Defeat/Vorban": 8253,
    "Creation Rewards/Wolf (3x)": 4533,
    "Creation Rewards/Reptile (3x)": 4534,
    "Creation Rewards/Bird (5x)": 4535,
    "Creation Rewards/Wasp (4x)": 4536,
    "Creation Rewards/Imp (4x)": 4537,
    "Creation Rewards/Eye (4x)": 4538,
    "Creation Rewards/Flan (3x)": 4539,
    "Creation Rewards/Element (3x)": 4540,
    "Creation Rewards/Helm (3x)": 4541,
    "Creation Rewards/Drake (4x)": 4542,
    "Creation Rewards/Fungus (5x)": 4543,
    "Creation Rewards/Bomb (5x)": 4544,
    "Creation Rewards/Ruminant (5x)": 4545,
    "Creation Rewards/Iron Giant (10x)": 4546,
    "Defeat/Fenrir": 8254,
    "Defeat/Ornitholestes": 8255,
    "Defeat/Pteryx": 8256,
    "Defeat/Hornet": 8257,
    "Defeat/Vidatu": 8258,
    "Defeat/One-Eye": 8259,
    "Defeat/Jumbo Flan": 8260,
    "Defeat/Nega Elemental": 8261,
    "Defeat/Tanket": 8262,
    "Defeat/Fafnir": 8263,
    "Defeat/Sleep Sprout": 8264,
    "Defeat/Bomb King": 8265,
    "Defeat/Juggernaut": 8266,
    "Defeat/Ironclad": 8267,
    "Creation Rewards/Area Conquest x2": 4547,
    "Creation Rewards/Species Conquest x2": 4548,
    "Creation Rewards/Area Conquest x6": 4549,
    "Creation Rewards/Species Conquest x6": 4550,
    "Creation Rewards/All Fiends x1": 4551,
    "Creation Rewards/All Fiends x5": 4552,
    "Creation Rewards/Underwater Fiends in Mt. Gagazet x2": 4553,
    "Creation Rewards/All Fiends x10": 4554,
    "Defeat/Earth Eater": 8268,
    "Defeat/Greater Sphere": 8269,
    "Defeat/Catastrophe": 8270,
    "Defeat/Th'uban": 8271,
    "Defeat/Neslug": 8272,
    "Defeat/Ultima Buster": 8273,
    "Defeat/Shinryu": 8274,
    "Defeat/Nemesis": 8275,
    "Bandersnatch (3x Wolf)/Captured": 36878,
    "Ahriman (4x Eye)/Captured": 36901,
    "Dark Flan (3x Flan)/Captured": 36884,
    "Grenade (5x Bomb)/Captured": 36950,
    "Grat/Captured": 36903,
    "Grendel (5x Ruminant)/Captured": 36913,
    "Bashura/Captured": 36922,
    "Mandragora/Captured": 36948,
    "Behemoth/Captured": 36933,
    "Splasher (2x Shinryu)/Captured": 36924,
    "Achelous (2x Shinryu)/Captured": 36909,
    "Maelspike (2x Shinryu)/Captured": 36910,
    "Raptor (3x Reptile)/Captured": 36887,
    "Gandarewa (5x Imp)/Captured": 36869,
    "Thunder Flan (3x Flan)/Captured": 36880,
    "Red Element (3x Elemental)/Captured": 36927,
    "Lamashtu (5x Drake)/Captured": 36915,
    "Funguar (5x Fungus)/Captured": 36915,
    "Garuda/Captured": 36904,
    "Zaurus (3x Reptile)/Captured": 36964,
    "Floating Death (4x Eye)/Captured": 36966,
    "Black Element (3x Elemental)/Captured": 36931,
    "Halma (3x Helm)/Captured": 36965,
    "Puroboros (5x Bomb)/Captured": 36959,
    "Spirit/Captured": 36960,
    "Machea/Captured": 36967,
    "Master Coeurl/Captured": 36938,
    "Master Tonberry/Captured": 36963,
    "Varuna/Captured": 36946,
    "Earth Eater/Defeated": 8268,
    "Greater Sphere/Defeated": 8269,
    "Catastrophe/Defeated": 8270,
    "Th'uban/Defeated": 8271,
    "Neslug/Defeated": 8272,
    "Ultima Buster/Defeated": 8273,
    "Shinryu/Defeated": 8274,
    "Nemesis/Defeated": 8275,
    "Fenrir/Defeated": 8254,
    "Ornitholestes/Defeated": 8255,
    "Pteryx/Defeated": 8256,
    "Hornet/Defeated": 8257,
    "Vidatu/Defeated": 8258,
    "One-Eye/Defeated": 8259,
    "Jumbo Flan/Defeated": 8260,
    "Nega Elemental/Defeated": 8261,
    "Tanket/Defeated": 8262,
    "Fafnir/Defeated": 8263,
    "Sleep Sprout/Defeated": 8264,
    "Bomb King/Defeated": 8265,
    "Juggernaut/Defeated": 8266,
    "Ironclad/Defeated": 8267,
    "Melusine (3x Reptile)/Captured": 36888,
    "Aerouge (4x Imp)/Captured": 36870,
    "Buer (4x Eye)/Captured": 36899,
    "Gold Element (3x Elemental)/Captured": 36928,
    "Kusariqqu (5x Drake)/Captured": 36916,
    "Larva/Captured": 36953,
    "Iron Giant (10x Iron Clad)/Captured": 36940,
    "Qactuar/Captured": 36951,
    "Blitzball Recruit - Brother/Brother": 28674,
    "Blitzball Recruit - Wakka/Wakka": 28692,
    "Rin/Recruit Rin": 28685,
    "Rin/Collect All Primers": 4501,
    "Before Evrae, Yellow Al Bhed on Left (NPC)/Al Bhed Potion x4 (NPC)": 4471,
    "Roof (Bosses)/Evrae": 8212,
    "Roof (Bosses)/Sin Left Fin": 8213,
    "Roof (Bosses)/Sin Right Fin": 8214,
    "Roof (Bosses)/Sinspawn Genais and Core": 8215,
    "Roof (Bosses)/Overdrive Sin": 8216,
    "Yellow Al Bhed, on Left (NPC)/Potion x 3": 4392,
    "Northeast Corner (Primer)/Al Bhed Primer I": 24577,
    "Defeat Tros (Boss)/Tros": 8193,
    "Northeast Structure (Chest)/200 gil": 4096,
    "Northwest Structure (Chest)/Potion x2": 4097,
    "West Branch of Main Path (Chest)/Hi-Potion x1": 4315,
    "Flint Inside Desk (Event)/Flint": 4099,
    "South Side of East Door (Chest)/X-Potion x1": 4309,
    "South End (Chest)/Ether": 4102,
    "Flowers in Sconce on Right Wall, North End (Event)/Withered Bouquet": 4098,
    "North exit from Stairs, East End (Chest)/Hi-Potion x1": 4103,
    "Defeat Klikk (Boss)/Klikk": 8192,
    "Defeat Geosgaeno (Boss)/Geosgaeno": 8240,
    "South Side Hidden Under Rocks (Chest)/Onion Knight": 4101,
    "Right Side (Chest)/Megalixir": 4300,
    "Left Side (Chest)/Mega Phoenix x4": 4301,
    "Release Anima (Event)/Anima": 12301,
    "East Alcove (Chest)/Moon Crest": 4364,
    "West Near Huts (Chest)/Antidote x2": 4105,
    "Aurochs (NPCs)/Hi-Potion x1 (Datto)": 4378,
    "Aurochs (NPCs)/Potion x3 (Jassu)": 4379,
    "Aurochs (NPCs)/Potion x2 (Botta)": 4380,
    "Aurochs (NPCs)/200 gil (Keepa)": 4381,
    "Dock (NPCs)/Remedy x1 (Kid)": 4382,
    "Dock (NPCs)/Seekers Ring (Priest)": 4383,
    "Dock (NPCs)/Phoenix Down x3 (Woman)": 4384,
    "Dock (NPCs)/400 gil (Shirtless Man)": 4385,
    "Dock (NPCs)/Ether (Green Shirt)": 4386,
    "Enter the Valley (Event)/Wakka": 12292,
    "South of Spawn, Right Side (Chest)/Phoenix Down x1": 4186,
    "South Side, Hidden Behind Right Wall (Chest)/Hi-Potion x1": 4187,
    "East Side, Right of Path (Chest)/Antidote x2": 4188,
    "Village Slope - Element Tutorial (Event)/Lulu": 12293,
    "Waterfall Way - Summon Tutorial (Event)/Yuna": 12289,
    "Monster Captures/Dingo (3x Wolf)": 36872,
    "Monster Captures/Condor (5x Bird)": 36891,
    "Monster Captures/Water Flan (3x Flan)": 36879,
    "Front of Shop (Chest)/Phoenix Down x1": 4109,
    "Behind Shop (Chests)/Hi-Potion x1": 4110,
    "Behind Shop (Chests)/400 gil": 4311,
    "Behind Shop (Chests)/Potion x2": 4312,
    "On Ground Near Counter (Primer)/Al Bhed Primer II": 24578,
    "Blitzball Recruit/Vilucha": 28691,
    "Summoning Cutscene (Event)/Valefor": 12296,
    "Exit the Village (Event)/Map": 4555,
    "Exit the Village (Event)/Brotherhood": 4304,
    "Defeat Dark Valefor (Superboss)/Dark Valefor": 8194,
    "Cloister of Trials/Destruction Sphere - Rod of Wisdom": 4111,
    "Corner South of Save Point (Primer)/Al Bhed Primer XXII": 24598,
    "Cloister of Trials/Knight Lance": 4198,
    "Cloister of Trials/Destruction Sphere - HP Sphere": 4313,
    "Cloister of Trials/Bahamut": 12300,
    "East Room With Kimahri (Chest)/Mega-Potion x1": 4206,
    "West Room With Lulu (Chest)/Wht Magic Sphere x1": 4201,
    "Southwest Room Near Glyph (Chest)/Elixir x1": 4200,
    "Room Northeast of Central Teleporter (Chest)/Blk Magic Sphere x1": 4205,
    "Puzzle Room (Chests)/Skill Sphere x1": 4202,
    "Puzzle Room (Chests)/10000 gil": 4203,
    "Puzzle Room (Chests)/Lucid Ring": 4204,
    "Defeat Isaaru (Boss)/Isaaru": 8218,
    "Defeat Evrae Altana (Boss)/Evrae Altana": 8219,
    "Right Side Before First Turn (Chest)/Rematch": 4197,
    "Right Side After First Turn (Chest)/Avenger": 4196,
    "Defeat Seymour Natus (Boss)/Seymour Natus": 8220,
    "In Southwest Corner of Water (Chest)/Remedy x4": 4442,
    "Northeast of Water (Primer)/Al Bhed Primer I": 24577,
    "Next to Tent (Chest & Primer)/Al Bhed Potion x8": 4306,
    "Next to Tent (Chest & Primer)/Al Bhed Primer III": 24579,
    "Behind Machinery Near Kimahri (Primer)/Al Bhed Primer V": 24581,
    "Near First Tent (Chests)/Ether x2": 4443,
    "Near First Tent (Chests)/Al Bhed Potion x8": 4307,
    "Western Alcove, Northeast of Structure (Primer)/Al Bhed Primer XIV": 24590,
    "Western Alcove, Near Structure (Chest)/Hi-Potion x4": 4444,
    "Structure Southeast of Save Sphere (Chest)/Hi-Potion x4": 4447,
    "Rock Ridge Southwest of Save Sphere (Chest)/X-Potion x2": 4446,
    "Far West Corner (Chest)/Mega-Potion x2": 4445,
    "Right of Save Sphere (Chest)/Al Bhed Potion x8": 4308,
    "Near Sign At Northeast Exit (Primer)/Al Bhed Primer XVIII": 24594,
    "Southwest Corner of Northwest Zone (Chest)/Elixir x1": 4448,
    "Central Structure of Northwest Zone (Chests)/Lv. 2 Key Sphere x1": 4450,
    "Central Structure of Northwest Zone (Chests)/10000 gil": 4449,
    "Northeast Structure of Northwest Zone (Primer)/Al Bhed Primer XVII": 24593,
    "Left Sinkhole on Main Path (Chest)/Megalixir x3": 4454,
    "Right Sinkhole on Main Path (Chest)/Teleport Sphere x2": 4455,
    "First Western Alcove (Chests)/Hi-Potion x8": 4451,
    "First Western Alcove (Chests)/Mercury Crest": 4369,
    "Second Western Alcove, Hidden Behind Rock (Chest)/Mega-Potion x3": 4452,
    "Second Western Alcove, North Side (Chest)/X-Potion x2": 4453,
    "Complete Cactuar Village Quest (Event)/Mercury Sigil": 4375,
    "Defeat Dark Ifrit (Superboss)/Dark Ifrit": 8211,
    "Keyakku, on Ground (NPC)/Hi-Potion x2": 4463,
    "Left of Entrance (Primer)/Al Bhed Primer XIX": 24595,
    "North Hall, Left (Chest)/Al Bhed Potion x6": 4456,
    "Northeast Corner (Primer)/Al Bhed Primer XXI": 24597,
    "East of Main Corridor (Chests)/Special Sphere x1": 4492,
    "East of Main Corridor (Chests)/Skill Sphere x1": 4491,
    "Hidden Behind Left Smoke (Chest)/Al Bhed Potion x4": 4457,
    "South of Main Corridor (Chests)/Friend Sphere x1": 4493,
    "South of Main Corridor (Chests)/Al Bhed Primer XX": 24596,
    "Area Completion/Lv. 2 Key Sphere x1": 4458,
    "Area Completion/Lv. 4 Key Sphere x4": 4459,
    "Area Completion/10000 gil": 4460,
    "Southeast Corner (Chests)/5000 gil": 4212,
    "Southeast Corner (Chests)/10000 gil": 4211,
    "Behind Agency Tent (Chest)/Lv. 2 Key Sphere x1": 4213,
    "Northwest Corner (Primer)/Al Bhed Primer XXIII": 24599,
    "Blitzball Recruit - Naida/Naida": 28683,
    "Blitzball Recruit - Svanda/Svanda": 28689,
    "Defeat Defender X (Boss)/Defender X": 8221,
    "Blitzball Recruit - Durren/Durren": 28675,
    "Rusty Sword Between Two Rocks, East End (Event)/Rusty Sword": 4214,
    "NW Corner, Blocked Until Winning Catcher Chocobo (Event)/Caladbolg": 4210,
    "Monster Arena/Nirvana": 4209,
    "Chocobo Training/Wobbly Chocobo Minigame (Event)": 4433,
    "Chocobo Training/Dodger Chocobo Minigame (Event)": 4434,
    "Chocobo Training/Hyper Dodger Chocobo Minigame (Event)": 4435,
    "Chocobo Training/Catcher Chocobo Minigame (Event)": 4436,
    "Chocobo Training/Sun Sigil (Catcher 0:00)": 4370,
    "First Branch East (Chest)/Megalixir x1": 4216,
    "Chamber East of First Intersection (Chest)/Lv. 2 Key Sphere x1": 4217,
    "Dead End North of Second Intersection (Chest)/Fortune Sphere x1": 4218,
    "Top of Third Intersection (Chest)/Mega-Potion x1": 4219,
    "Dead End West of Third Intersection (Primer)/Al Bhed Primer XXV": 24601,
    "Teleport West from Back of Cavern (Chest)/Flexible Arm": 4220,
    "Teleport East from Back of Cavern (Chests)/MP Sphere x1": 4221,
    "Teleport East from Back of Cavern (Chests)/X-Potion x2": 4222,
    "Chamber of the Fayth/Yojimbo": 12302,
    "Defeat Dark Yojimbo (Superboss)/Dark Yojimbo": 8223,
    "South End, West Side (Chest)/Phoenix Down x2": 4150,
    "South End, Behind Left Pillar (Primer)/Al Bhed Primer XI": 24587,
    "South End, Purple Armor (NPC)/Soft Ring": 4394,
    "Midway, Yellow Armor (NPC)/Ether x1": 4396,
    "Monk Pacing Between Crusaders (NPC)/Hi-Potion x1": 4395,
    "North End, Purple Armor (NPC)/Mega-Potion x1": 4397,
    "South End, Silver & Purple Armor (NPC)/Variable Steel": 4393,
    "Midway, Hidden in Western Alcove (Chest)/Bright Bangle": 4151,
    "Northeast Corner (Chest)/Ability Sphere x4": 4154,
    "West Behind Lucil's Squad (Chest)/4000 gil": 4155,
    "In Front of Nuns' Chamber (Chest)/Ether x1": 4157,
    "Nuns' Chamber (Chest)/Remedy x1": 4158,
    "Monks' Chamber (Chest)/Mega Phoenix x1": 4159,
    "Cloister of Trials/Destruction Sphere - Magic Sphere": 4580,
    "Chamber of the Fayth/Ixion": 12298,
    "Behind Desk (Chest)/Switch Hitter": 4156,
    "North End, Purple Armor (NPC)/Halberd": 4398,
    "South End, Silver & Purple Armor (NPC)/Potion x10": 4399,
    "South End, Silver & Purple Armor (NPC)/Recruit: Kyou": 28678,
    "Monk Pacing Along Bridge (NPC)/Hi-Potion x2": 4400,
    "Monster Captures/Raptor (3x Reptile)": 36887,
    "Monster Captures/Gandarewa (5x Imp)": 36869,
    "Monster Captures/Lamashtu (5x Drake)": 36915,
    "Monster Captures/Funguar (5x Fungus)": 36915,
    "Monster Captures/Garm (3x Wolf)": 36874,
    "Monster Captures/Simurgh (5x Bird)": 36892,
    "Monster Captures/Bite Bug (4x Hornet)": 36895,
    "Monster Captures/Snow Flan (3x Flan)": 36881,
    "Monster Captures/Bunyip (3x Helm)": 36865,
    "Monster Captures/Basilisk": 36943,
    "East of Mansion (Chest)/Mega-Potion x1": 4161,
    "House - On Floor (Primer)/Al Bhed Primer XIII": 24589,
    "House - Back Wall (Chest)/3000 gil": 4160,
    "Upper Level, South Side (Chest)/Elixir x1": 4162,
    "Mansion, Entrance - Upper Level (Chest)/Hi-Potion x2": 4163,
    "Blitzball Recruit/Yuma Guado": 28694,
    "Road to Farplane - Left Side Behind Wall (Chest)/Lightning Marble x8": 4314,
    "Automatic Upon Leaving Farplane (Event)/Brotherhood Upgrade": 24613,
    "Second Visit, West Side (Chest)/Venus Crest": 4368,
    "West Alcove (Chest)/Phantom Ring": 4262,
    "Atop Western Falls (Chest)/Special Sphere x1": 4263,
    "Northwestern Alcove (Chest)/Elixir x1": 4259,
    "Atop Eastern Falls (Chest)/Wizard Lance": 4260,
    "Eastern Alcove, Near Final North Branch (Chest)/Lv. 3 Key Sphere x1": 4261,
    "Defeat Seymour Omnis (Boss)/Seymour Omnis": 8231,
    "East Glyph Near South Exit, Defeat 10-10-15 Fiends (Chest)/Lv. 4 Key Sphere x1": 4264,
    "South Side, Lift on Small Bridge (Chest)/Four-on-One": 4265,
    "South of First Open Area, Push North Wall Down (Chest)/Defending Bracer": 4266,
    "First Open Area, Ramp Down in Center (Chest)/20000 gil": 4267,
    "First Open Area, Glyph in Northwest Corner (Chest)/Megalixir x1": 4270,
    "Lift Up in Center of First Open Area (Chest)/HP Sphere x1": 4268,
    "Lift Up in Center of First Area, Just Before Lift Down (Chest)/Defense Sphere x1": 4269,
    "Secret Slide South of Rising Block Area (Chest)/Laevatein": 4271,
    "Right of Collapsing House (Chest)/Potion x3": 4113,
    "After Rescuing Kulukan's Sister from Collapsing House (Chest)/Ether x1": 4114,
    "On Counter (Primer)/Al Bhed Primer IV": 24580,
    "Blitzball Recruit/Tatts": 28690,
    "East of First Intersection (Chest)/Mana Sphere x2": 4123,
    "West of First Intersection, First North Fork (Chest)/Scout": 4124,
    "Crusader Commander West of Lord Ochu (NPC)/Remedy x1": 4389,
    "Crusader Commander North of Lord Ochu (NPC)/High Potion x1": 4391,
    "Path North of Lord Ochu, Curving West (Chest)/Luck Sphere x1": 4125,
    "Defeat Lord Ochu (Boss)/Lord Ochu": 8197,
    "Luzzu (NPC)/Antidote x4 (Before Defeating Ochu)": 4387,
    "Luzzu (NPC)/Elixir x1 (After Defeating Ochu)": 4388,
    "Defeat Sinspawn Geneaux (Boss)/Sinspawn Geneaux": 8198,
    "Monster Captures/Dinonix (3x Reptile)": 36885,
    "Monster Captures/Killer Bee (5x Wasp)": 36894,
    "Monster Captures/Yellow Element (3x Elemental)": 36925,
    "Monster Captures/Ragora": 36902,
    "Blitzball Recruit/Mep": 28680,
    "Cloister of Trials/Destruction Sphere - Red Armlet": 4115,
    "Chamber of the Fayth/Ifrit": 12297,
    "West Locker Hall (Chest)/Hi-Potion x2": 4132,
    "Behind Isken (Primer)/Al Bhed Primer VI": 24582,
    "Win the Story Blitzball Tournament (Event)/Story Win vs. Luca Goers Reward": 4593,
    "Post-Blitzball Tournament (Event)/Auron": 12290,
    "Blitzball Recruit - Biggs & Wedge/Biggs": 28673,
    "Blitzball Recruit - Biggs & Wedge/Wedge": 28693,
    "Inside Back Right Locker (Event)/Jupiter Crest": 4367,
    "Obtain The Jupiter Sigil League Prize (Event)/Jupiter Sigil": 4340,
    "Dock 1 - Right Side (Chest)/600 Gil": 4129,
    "Dock 1 - End (Chest)/Tidal Spear": 4130,
    "Dock 2 - Left Side (Chest)/Phoenix Down x2": 4128,
    "Dock 5 - End, Hidden Behind Boxes (Chests)/HP Sphere x1": 4131,
    "Dock 5 - End, Hidden Behind Boxes (Chests)/Magic Sphere x1": 4302,
    "Blitzball Recruit - Nedus/Nedus": 28684,
    "Blitzball Recruit - Zev Ronso/Zev Ronso": 28696,
    "Defeat Oblitzerator (Boss)/Oblitzerator": 8199,
    "Bottom of Stairs, Left Side (Primer)/Al Bhed Primer VII": 24583,
    "Staircase Leading to Mi'ihen (Chest)/1000 Gil": 4133,
    "Blitzball Recruit - Jumal/Jumal": 28676,
    "Blitzball Recruit - Shaami/Shaami": 28687,
    "Blitzball Recruit - Shuu/Shuu": 28688,
    "Blitzball Recruit - Zalitz/Zalitz": 28695,
    "Talk to Owner After Placing at Least Third in a Tournament (Chest)/World Chamnpion": 4189,
    "Celestial Flower/Celestial Mirror": 4207,
    "Celestial Flower/Tidus - Caladbolg Crest Upgrade": 24614,
    "Celestial Flower/Tidus - Caladbolg Sigil Upgrade": 24615,
    "Celestial Flower/Yuna - Nirvana Crest Upgrade": 24616,
    "Celestial Flower/Yuna - Nirvana Sigil Upgrade": 24617,
    "Celestial Flower/Auron - Masamune Crest Upgrade": 24618,
    "Celestial Flower/Auron - Masamune Sigil Upgrade": 24619,
    "Celestial Flower/Kimahri - Spirit Lance Crest Upgrade": 24620,
    "Celestial Flower/Kimahri - Spirit Lance Sigil Upgrade": 24621,
    "Celestial Flower/Wakka - World Champion Crest Upgrade": 24622,
    "Celestial Flower/Wakka - World Champion Sigil Upgrade": 24623,
    "Celestial Flower/Lulu - Onion Knight Crest Upgrade": 24624,
    "Celestial Flower/Lulu - Onion Knight Sigil Upgrade": 24625,
    "Celestial Flower/Rikku - Godhand Crest Upgrade": 24626,
    "Celestial Flower/Rikku - Godhand Sigil Upgrade": 24627,
    "Hidden Behind Tree in Middle of S-Bend (Chest)/Sleepy Cait Sith": 4165,
    "Near North Exit (Chest)/2000 gil": 4164,
    "Hidden Behind Tree Before Spiral Down (Chest)/Phoenix Down x3": 4166,
    "Hidden Behind Tree on West Side (Chest)/Remedy x1": 4169,
    "Near Southeast Exit (Primer)/Al Bhed Primer XV": 24591,
    "Defeat Spherimorph (Boss)/Spherimorph": 8206,
    "Campsite (Chest)/Lucid Ring": 4171,
    "Butterfly Minigame (Event)/Saturn Sigil": 4373,
    "Monster Captures/Iguion (3x Reptile)": 36889,
    "Monster Captures/Wasp (4x Wasp)": 36896,
    "Monster Captures/Blue Element (3x Elemental)": 36929,
    "Monster Captures/Murussu (3x Helm)": 36866,
    "Monster Captures/Xiphos": 36958,
    "Monster Captures/Chimera": 36935,
    "Left Side (Primer)/Al Bhed Primer XVI": 24592,
    "Right Side (Chest)/4000 gil": 4172,
    "Cross the Lake (Boss)/Crawler": 8207,
    "Cross the Lake (Boss)/Wendigo": 8209,
    "South End of Narrow Path (Chest)/Lv. 1 Key Sphere x1": 4173,
    "Near North Exit (Chest)/Mega-Potion x1": 4174,
    "Linna, at Bottom of Stairs (NPC)/400 gil": 4401,
    "Linna, at Bottom of Stairs (NPC)/Recruit": 28679,
    "Defeat Dark Shiva (Superboss)/Dark Shiva": 8210,
    "Hidden Behind Kimahri (Chest)/Lv. 2 Key Sphere": 4176,
    "Hidden Left of Auron (Chest)/Avenger": 4175,
    "Monster Captures/Snow Wolf (3x Wolf)": 36875,
    "Monster Captures/Evil Eye (4x Eye)": 36900,
    "Monster Captures/Ice Flan (3x Flan)": 36882,
    "Monster Captures/Mafdet (3x Helm)": 36867,
    "Automatic upon Entering (Event)/Shell Targe": 4181,
    "North Side (Chest)/5000 gil": 4179,
    "South Side (Chest)/X-Potion x2": 4180,
    "Nuns' Chamber (Chest)/Remedy x2": 4183,
    "Nuns' Chamber - Yellow Nun (NPC)/Hi-Potion x2": 4404,
    "Monks' Chamber- Brown Monk (NPC)/Ether x1": 4403,
    "Monks' Chamber- Purple Monk (NPC)/Elixir x1": 4402,
    "Monks' Chamber (Chest)/Phoenix Down x3": 4182,
    "Defeat Seymour (Boss)/Seymour": 8208,
    "Cloister of Trials/Destruction Sphere - Luck Sphere": 4581,
    "Chamber of the Fayth/Shiva": 12299,
    "Yellow Man, Looping South to North (NPC)/Hi-Potion": 4407,
    "Blue-White Man, Looping North to South (NPC)/Hunters Spear": 4405,
    "Red Skirt Girl, Pacing Between Maechen and Ruins (NPC)/Antidote x2": 4406,
    "Behind Ruins on Left (Chest)/Ice Brand": 4134,
    "Behind Elma, North Side (Chest)/Remedy x1": 4140,
    "Crusader Running East then West (NPC)/Red Ring": 4409,
    "Boy Before Kicking the Blitzball (NPC)/Soft x3": 4408,
    "Purple Crusader, Looping South to North (NPC)/Lv. 1 Key Sphere x1": 4413,
    "Female Yellow Crusader, Looping North to South (NPC)/Antidote x4": 4414,
    "East Alcove (Chest)/2000 gil": 4141,
    "Yellow Crusader, Looping North to South (NPC)/600 gil": 4412,
    "Purple Crusader Freaking Out, West Side (NPC)/Ether x1": 4410,
    "Woman on North End, West Side (NPC)/Hi-Potion x1": 4411,
    "North Exit (Chest)/Eye Drops x3": 4142,
    "Green NPC After Resting (Event)/Lv. 1 Key Sphere x1": 4519,
    "Exit After Resting (Event)/Mega-Potion": 4193,
    "Exit After Resting (Event)/Al Bhed Primer VIII": 24584,
    "Blitzball Recruit/Ropp": 28686,
    "Defeat Chocobo Eater (Boss)/Chocobo Eater": 8200,
    "Chocobo Jump North Peak of Bend (Chest)/Heat Lance": 4138,
    "Peak of South Bend Before Shelinda (Primer)/Al Bhed Primer IX": 24585,
    "Left by Child Soldiers (Chest)/Hi-Potion x2": 4139,
    "Chocobo Jump, Left Side (Chests)/Thunder Blade": 4136,
    "Chocobo Jump, Left Side (Chests)/Scout": 4137,
    "Chocobo Jump, Alcove on East Side (Chest)/Fortune Sphere": 4135,
    "South End (Chest)/Mars Crest": 4365,
    "Monster Captures/Miihen Fang (3x Wolf)": 36873,
    "Monster Captures/Ipiria (3x Reptile)": 36886,
    "Monster Captures/Floating Eye (4x Eye)": 36886,
    "Monster Captures/White Element (3x Elemental)": 36926,
    "Monster Captures/Raldo (3x Armoured)": 36864,
    "Monster Captures/Vouivre (5x Drake)": 36914,
    "Monster Captures/Bomb (5x Bomb)": 36949,
    "Monster Captures/Dual Horn (5x Ruminant)": 36911,
    "Monster Captures/Thunder Flan (3x Flan)": 36880,
    "Right of Shelinda (Chest)/Lv. 1 Key Sphere x3": 4472,
    "West Corner as Path Bends East (Chest)/X-Potion x1": 4293,
    "East Alcove as Path Bends North (Chest)/Lv. 1 Key Sphere x3": 4473,
    "West Alcove in Forest Past Belgemine (Chest)/Magic Def Sphere x1": 4474,
    "Near O'aka XXIII (Chest)/Phoenix Down x2": 4294,
    "Behind Lulu (Chest)/5000 gil": 4295,
    "Defeat Extractor (Boss)/Extractor": 8204,
    "Up Slope Right of Hypello (Primer)/Al Bhed Primer XII": 24588,
    "Near Bench (Chest)/Ether x1": 4296,
    "Blitzball Recruit/Miyu": 28682,
    "Mix Tutorial (Event)/Rikku": 12294,
    "East Side, Right After the Wooden Bridge (Chest)/Antidote x4": 4297,
    "West Side, Before Guadosalam (Chest)/Mega-Potion x1": 4298,
    "Monster Captures/Ochu": 36947,
    "Defeat Biran and Yenke (Boss)/Biran and Yenke": 8224,
    "Top of Right Ridge Near South Exit (Chest)/20000 gil": 4224,
    "Left Alcove Near South Exit (Chest)/Mega-Potion x2": 4225,
    "West Branch Before Bridge to Wantz (Chest)/Defending Bracer": 4226,
    "Under Bridge After Wantz (Chests)/Lv. 4 Key Sphere x1": 4227,
    "Under Bridge After Wantz (Chests)/HP Sphere x1": 4228,
    "Defeat Seymour Flux (Boss)/Seymour Flux": 8225,
    "Hidden Between Left Pillars (Chest)/Saturn Crest": 4366,
    "Defeat Dark Anima (Superboss)/Dark Anima": 8226,
    "Reward from First Trial (Chest)/Lv. 1 Key Sphere x1": 4232,
    "Reward From Second Trial (Chest)/Fortune Sphere x1": 4233,
    "After Both Trials, East Exit From Save Sphere (Chests)/Return Sphere x1": 4234,
    "After Both Trials, East Exit From Save Sphere (Chests)/Recovery Ring": 4235,
    "After Both Trials, Left Alcove, Northwest of Save Sphere (Chest)/Pep Talk": 4231,
    "Defeat Sanctuary Keeper (Boss)/Sanctuary Keeper": 8227,
    "Left Near Southern Exit (NPC)/Remedy x1": 4417,
    "Right Near Southern Exit (NPC)/Tough Bangle": 4415,
    "Pacing Between Blue Commander and South Exit (NPC)/Ether x1": 4419,
    "Blue Commander on Left Side (NPC)/Hi-Potion x1": 4418,
    "Pacing Between Blue Commander and North Exit (NPC)/Phoenix Down x2": 4416,
    "Dark Magus Sisters (Superboss)/Dark Cindy": 8239,
    "Dark Magus Sisters (Superboss)/Dark Mindy": 8237,
    "Dark Magus Sisters (Superboss)/Dark Sandy": 8238,
    "Woman Before First Elevator (NPC)/Hi-Potion x1": 4420,
    "North Alcove After First Elevator (Chest & NPC)/1000 gil": 4144,
    "North Alcove After First Elevator (Chest & NPC)/Potion x10": 4421,
    "Left Side, As Trail Turns East (Chest)/Remedy x1": 4146,
    "Behind Pillar, Before Second Elevator (Chest)/Hi-Potion x1": 4145,
    "Near South Elevator (NPC)/X-Potion x1": 4423,
    "Below West Elevator (Chest)/Serene Armlet": 4153,
    "End of Curved Path West of North Elevator (Primer)/Al Bhed Primer X": 24586,
    "Pacing Between North Elevator and East Ridge (NPC)/400 gil": 4422,
    "Near Large Elevator (NPC)/Mega-Potion x1": 4424,
    "Near Lulu (Chest)/Mega-Potion x1": 4148,
    "Behind Spear Rack (Chest)/Serene Bracer": 4147,
    "Defeat Sinspawn Gui (Boss)/Sinspawn Gui": 8201,
    "Defeat Sinspawn Gui (Boss)/Sinspawn Gui 2": 8202,
    "Defeat Sinspawn Gui (Boss)/Seymour": 12295,
    "Under Overhang, West Side (Chest)/Hi-Potion x1": 4194,
    "Left Exit Over Boxes (Chest)/Soft x4": 4143,
    "Up Elevator in West Alcove, North Side (Event)/Masamune": 4195,
    "Monster Captures/Red Element (3x Elemental)": 36927,
    "Monster Captures/Garuda": 36904,
    "Press Both Glyphs, Then Take Narrow Central Path (Chest)/Teleport Sphere x1": 4426,
    "North Side of Four Chest Intersection (Primer)/Al Bhed Primer XXVI": 24602,
    "Defeat Ultima Weapon (Boss)/Ultima Weapon": 8235,
    "West Path (Chest)/Friend Sphere x1": 4427,
    "Defeat Omega Weapon (Superboss)/Omega Weapon": 8236,
    "Omega Boss Arena (Chest)/Magic Sphere x1": 4428,
    "Northwest Corner (Primer)/Al Bhed Primer XXIV": 24600,
    "Win Chocobo Race (Event)/Cloudy Mirror": 4272,
    "Belgemine/Valefor Fight": 4475,
    "Belgemine/Ifrit Fight": 4477,
    "Belgemine/Ixion Fight": 4479,
    "Belgemine/Shiva Fight": 4481,
    "Belgemine/Bahamut Fight": 4430,
    "Belgemine/Yojimbo Fight": 4484,
    "Belgemine/Anima Fight": 4486,
    "Belgemine/Magus Sisters Fight": 4488,
    "Defeat All Aeons and Send Belgemine (Event)/Moon Sigil": 4371,
    "Chamber of the Fayth/Magus Sisters": 12303,
    "Cabin (Chest)/Remedy x1": 4112,
    "Bottom Right Corner (Primer)/Al Bhed Primer III": 24579,
    "Encounter Sin Fin (Event)/Kimahri": 12291,
    "Encounter Sin Fin (Event)/Sin Fin": 8195,
    "Encounter Sin Fin (Event)/Sinspawn Echuilles": 8196,
    "Left, Between Aurochs and Goers (Chest)/Hi-Potion x1": 4127,
    "On Floor Behind Captain (Primer)/Al Bhed Primver V": 24581,
    "Blitzball Recruit (2nd Visit)/Kiyuri": 28677,
    "Top Floor, Counting Gulls (2nd Visit, NPC - 11 Seagulls)/Ace Wizard": 4461,
    "West Side, South of Save Sphere (Chest)/Phoenix Down x2": 4274,
    "West Side, North of Save Sphere (Chest)/Hi-Potion x2": 4275,
    "West Side, Behind First Cactuar Statue (Chest)/5000 gil": 4276,
    "East Side, Alcove With Second Cactuar Statue (Chest)/Water Ball": 4277,
    "Cactuar Statue Minigame (Event)/Spirit Lance": 4284,
    "Blitzball Recruit/Mifurey": 28681,
    "Talk to Rikku, Then Rin (Event)/Al Bhed Primer XIV": 24590,
    "Agency Front (Ground Item)/Yellow Shield": 4441,
    "Lightning Dodging/X-Potion x2 (5x Dodges)": 4285,
    "Lightning Dodging/Mega-Potion x2 (10x Dodges)": 4286,
    "Lightning Dodging/MP Sphere x2 (20x Dodges)": 4287,
    "Lightning Dodging/Strength Sphere x3 (50x Dodges)": 4288,
    "Lightning Dodging/HP Sphere x3 (100x Dodges)": 4289,
    "Lightning Dodging/Megalixir x4 (150x Dodges)": 4290,
    "Lightning Dodging/Venus Sigil (200x Dodges)": 4374,
    "East Side, Near Southeast Exit (Chest)/X-Potion x1": 4278,
    "West Side, Behind Sheltered Lightning Rod (Chest)/Ether x1": 4279,
    "East of Final Lightning Rod (Chest)/2000 gil": 4281,
    "West Side, Near North Exit (Chest)/Remedy x1": 4280,
    "Defeat Dark Ixion (Superboss)/Dark Ixion": 8205,
    "Monster Captures/Melusine (3x Reptile)": 36888,
    "Monster Captures/Aerouge (4x Imp)": 36870,
    "Monster Captures/Buer (4x Eye)": 36899,
    "Monster Captures/Gold Element (3x Elemental)": 36928,
    "Monster Captures/Kusariqqu (5x Drake)": 36916,
    "Monster Captures/Larva": 36953,
    "Monster Captures/Iron Giant (10x Iron Clad)": 36940,
    "Monster Captures/Qactuar": 36951,
    "South Side, West Bend (Chest)/Fortune Sphere x1": 4241,
    "North Side, Left Alcove (Chest)/Spiritual Targe": 4242,
    "Road Above Underpass (Chest)/10000 gil": 4243,
    "West From 4-Way Intersection (Chest)/Friend Sphere x1": 4244,
    "Rubble Path Down Before Circular Doorway (Chest)/Lv. 3 Key Sphere x1": 4245,
    "Right Side (Chest)/Luck Sphere x1": 4246,
    "Defeat Spectral Keeper (Boss)/Spectral Keeper": 8228,
    "Defeat Yunalesca (Boss)/Yunalesca": 8229,
    "Chest After Taking Left/Right in Yunalesca Arena (Chest)/Sun Crest": 4363,
    "Cloister of Trials/Destruction Sphere- Magistral Rod": 4305,
    "Defeat Dark Bahamut (Superboss)/Dark Bahamut": 8230,
    "Baaj Temple/Submerged Ruins - 200 gil (Chest)": 4096,
    "Baaj Temple/Submerged Ruins - Potion x2 (Chest)": 4097,
    "Baaj Temple/Underwater Hall - Hi-Potion x1 (Chest)": 4315,
    "Baaj Temple/Small Room - Flint": 4099,
    "Baaj Temple/Hall - X-Potion x1 (Chest)": 4309,
    "Baaj Temple/Stairs - Ether (Chest)": 4102,
    "Baaj Temple/Stairs - Withered Bouquet": 4098,
    "Baaj Temple/Hall - Hi-Potion x1 (Chest)": 4103,
    "Baaj Temple/Hall - Klikk": 8192,
    "Baaj Temple/Underwater Hall - Geosgaeno": 8240,
    "Baaj Temple/Underwater Hall - Onion Knight (Chest)": 4101,
    "Baaj Temple/Antechamber - Megalixir (Chest)": 4300,
    "Baaj Temple/Antechamber - Mega Phoenix x4 (Chest)": 4301,
    "Baaj Temple/Antechamber - Anima": 12301,
    "Al Bhed Ship/Deck - Potion x 3 (NPC)": 4392,
    "Al Bhed Ship/Deck- Al Bhed Primer I": 24577,
    "Al Bhed Ship/Sunken Ruins - Tros": 8193,
    "Besaid/Beach - Antidote x2 (Chest)": 4105,
    "Besaid/Beach - Moon Crest (Chest)": 4364,
    "Besaid/Beach - Aurochs (Datto)": 4378,
    "Besaid/Beach - Aurochs (Jassu)": 4379,
    "Besaid/Beach - Aurochs (Botta)": 4380,
    "Besaid/Beach - Aurochs (Keepa)": 4381,
    "Besaid/Valley - Wakka": 12292,
    "Besaid/Valley - Phoenix Down x1 (Chest)": 4186,
    "Besaid/Valley - Hi-Potion x1 (Chest)": 4187,
    "Besaid/Valley - Antidote x2 (Chest)": 4188,
    "Besaid/Village - Phoenix Down x1 (Chest)": 4109,
    "Besaid/Village - Behind the Shop (Bottom Chest)": 4110,
    "Besaid/Village - Behind the Shop (Middle Chest)": 4311,
    "Besaid/Village - Behind the Shop (Top Chest)": 4312,
    "Besaid/Village - Al Bhed Primer II": 24578,
    "Besaid/Village - Recruit Vilucha": 28691,
    "Besaid/Temple - Cloister of Trials - Destruction Sphere": 4111,
    "Besaid/Village - Cloister of Trials - Valefor": 12296,
    "Besaid/Village - Exit the Village (Map)": 4555,
    "Besaid/Village - Exit the Village (Brotherhood)": 4304,
    "Besaid/Village Slope - Lulu": 12293,
    "Besaid/Waterfall Way - Yuna": 12289,
    "Besaid/Beach - Dock (Kid))": 4382,
    "Besaid/Beach - Dock (Priest))": 4383,
    "Besaid/Beach - Dock (Woman))": 4384,
    "Besaid/Beach - Dock (Shirtless Man))": 4385,
    "Besaid/Beach - Dock (Green Shirt))": 4386,
    "Besaid/Super Bosses - Dark Valefor": 8194,
    "S.S. Liki/Remedy x1 (Chest)": 4112,
    "S.S. Liki/Al Bhed Primer III": 24579,
    "S.S. Liki/Kimahri": 12291,
    "S.S. Liki/Sin Fin": 8195,
    "S.S. Liki/Sinspawn Echuilles": 8196,
    "Kilika/Village - Potion x3 (Chest)": 4113,
    "Kilika/Village - Ether x1 (Chest)": 4114,
    "Kilika/Village - Al Bhed Primer IV": 24580,
    "Kilika/Village - Recruit Tatts": 28690,
    "Kilika/Woods - Mana Sphere x2 (Chest)": 4123,
    "Kilika/Woods - Scout (Chest)": 4124,
    "Kilika/Woods - Remedy x1 (Leader NPC)": 4389,
    "Kilika/Woods - High Potion x1 (Guard NPC)": 4391,
    "Kilika/Woods - Luck Sphere x1 (Chest)": 4125,
    "Kilika/Woods - Luzzu - Before Ochu (NPC)": 4387,
    "Kilika/Woods - Lord Ochu": 8197,
    "Kilika/Woods - Luzzu - After Ochu (NPC)": 4388,
    "Kilika/Woods - Sinspawn Geneaux": 8198,
    "Kilika/Temple - Recruit Mep": 28680,
    "Kilika/Temple - Cloister of Trials": 4115,
    "Kilika/Temple - Ifrit": 12297,
    "S.S. Winno/Hi-Potion x1 (Chest)": 4127,
    "S.S. Winno/Al Bhed Primer V": 24581,
    "S.S. Winno/Recruit Kiyuri": 28677,
    "S.S. Winno/Ace Wizard (11 Seagulls)": 4461,
    "Luca/Stadium Basement B - Hi-Potion x2 (Chest)": 4132,
    "Luca/Stadium Basement B - Al Bhed Primer VI": 24582,
    "Luca/Dock 1 - 600 Gil (Chest)": 4129,
    "Luca/Dock 1 - Tidal Spear (Chest)": 4130,
    "Luca/Dock 2 - Phoenix Down x2 (Chest)": 4128,
    "Luca/Dock 5 - HP Sphere x1 (Chest)": 4131,
    "Luca/Dock 5 - Magic Sphere x1 (Chest)": 4302,
    "Luca/Theater Reception - Al Bhed Primer VII": 24583,
    "Luca/City Limits - 1000 Gil (Chest)": 4133,
    "Luca/Dock - Recruit Nedus": 28684,
    "Luca/Dock - Recruit Zev Ronso": 28696,
    "Luca/Stadium - Recruit Biggs": 28673,
    "Luca/Stadium - Recruit Wedge": 28693,
    "Luca/City - Recruit Jumal": 28676,
    "Luca/City - Recruit Shaami": 28687,
    "Luca/City - Recruit Zalitz": 28695,
    "Luca/Dock - Oblitzerator": 8199,
    "Luca/Stadium - Story Win vs. Luca Goers Reward": 4593,
    "Luca/Stadium - Auron": 12290,
    "Luca/Stadium Locker Room - Jupiter Crest (Locker)": 4367,
    "Luca/City - Recruit Shuu": 28688,
    "Luca/City Cafe - World Champion": 4189,
    "Luca/Blitzball - Jupiter Sigil (Blitzball League)": 4340,
    "Miihen Highroad/South - Hi-Potion (Yellow Shirt NPC)": 4407,
    "Miihen Highroad/South - Hunters Spear (Blue Shirt NPC)": 4405,
    "Miihen Highroad/South - Antidote x2 (Red Skirt NPC)": 4406,
    "Miihen Highroad/South - Ice Brand (Chest)": 4134,
    "Miihen Highroad/South - Remedy x1 (Chest)": 4140,
    "Miihen Highroad/South - Red Ring (Crusader NPC)": 4409,
    "Miihen Highroad/South - Soft x3 (Boy NPC)": 4408,
    "Miihen Highroad/Central - Lv. 1 Key Sphere x1 (Purple Crusader NPC)": 4413,
    "Miihen Highroad/Central - Antidote x4 (Woman in Yellow NPC)": 4414,
    "Miihen Highroad/Central - 2000 gil (Chest)": 4141,
    "Miihen Highroad/Central - 600 gil (Yellow Crusader NPC)": 4412,
    "Miihen Highroad/Central - Ether x1 (NPC)": 4410,
    "Miihen Highroad/Central - Hi-Potion x1 (NPC)": 4411,
    "Miihen Highroad/Central - Eye Drops x3 (Chest)": 4142,
    "Miihen Highroad/Agency - Lv. 1 Key Sphere x1 (NPC)": 4519,
    "Miihen Highroad/Agency - Mega-Potion (NPC)": 4193,
    "Miihen Highroad/Agency - Al Bhed Primer VIII": 24584,
    "Miihen Highroad/Agency - Recruit Ropp": 28686,
    "Miihen Highroad/Agency - Chocobo Eater": 8200,
    "Miihen Highroad/Newroad - Heat Lance (Chest)": 4138,
    "Miihen Highroad/Newroad - Al Bhed Primer IX": 24585,
    "Miihen Highroad/Newroad - Hi-Potion x2 (Chest)": 4139,
    "Miihen Highroad/Oldroad - Thunder Blade (Chest)": 4136,
    "Miihen Highroad/Oldroad - Scout (Chest)": 4137,
    "Miihen Highroad/Oldroad - Fortune Sphere (Chest)": 4135,
    "Miihen Highroad/Oldroad - Mars Crest (Chest)": 4365,
    "Mushroom Rock Road/Entrance - Remedy x1 (Near Grey Helmet NPC)": 4417,
    "Mushroom Rock Road/Entrance - Tough Bangle (Gray Helmet NPC)": 4415,
    "Mushroom Rock Road/Entrance - Ether x1 (Purple Helmet NPC)": 4419,
    "Mushroom Rock Road/Entrance - Hi-Potion x1 (Woman in Blue NPC)": 4418,
    "Mushroom Rock Road/Entrance - Phoenix Down x2 (Blue Shirt Crusader NPC)": 4416,
    "Mushroom Rock Road/Valley - Hi-Potion x1 (Woman NPC near Save Point)": 4420,
    "Mushroom Rock Road/Valley - 1000 gil (Chest)": 4144,
    "Mushroom Rock Road/Valley - Potion x10 (NPC near chest)": 4421,
    "Mushroom Rock Road/Valley - Remedy x1 (Chest)": 4146,
    "Mushroom Rock Road/Valley - Hi-Potion x1 (Chest)": 4145,
    "Mushroom Rock Road/Precipice - X-Potion x1 (NPC near lift)": 4423,
    "Mushroom Rock Road/Precipice - Serene Armlet (Chest)": 4153,
    "Mushroom Rock Road/Precipice - Al Bhed Primer X": 24586,
    "Mushroom Rock Road/Precipice - 400 gil (NPC near elevator)": 4422,
    "Mushroom Rock Road/Precipice - Mega-Potion x1 (NPC)": 4424,
    "Mushroom Rock Road/Ridge - Mega-Potion x1 (Chest)": 4148,
    "Mushroom Rock Road/Ridge - Serene Bracer (Chest)": 4147,
    "Mushroom Rock Road/Ridge - Sinspawn Gui": 8201,
    "Mushroom Rock Road/Ridge - Sinspawn Gui 2": 8202,
    "Mushroom Rock Road/Ridge - Seymour": 12295,
    "Mushroom Rock Road/Aftermath - Hi-Potion x1 (Chest)": 4194,
    "Mushroom Rock Road/Aftermath - Soft x4 (Chest)": 4143,
    "Mushroom Rock Road/Aftermath - Masamune": 4195,
    "Mushroom Rock Road/Super Bosses - Dark Cindy": 8239,
    "Mushroom Rock Road/Super Bosses - Dark Mindy": 8237,
    "Mushroom Rock Road/Super Bosses - Dark Sandy": 8238,
    "Djose/Highroad - Phoenix Down x2 (Chest)": 4150,
    "Djose/Highroad - Al Bhed Primer XI": 24587,
    "Djose/Highroad - Soft Ring (NPC)": 4394,
    "Djose/Highroad - Ether x1 (NPC)": 4396,
    "Djose/Highroad - Hi-Potion x1 (NPC)": 4395,
    "Djose/Highroad - Mega-Potion x1 (NPC)": 4397,
    "Djose/Highroad - Variable Steel (NPC)": 4393,
    "Djose/Highroad - Bright Bangle (Chest)": 4151,
    "Djose/Temple - Ability Sphere x4 (Chest)": 4154,
    "Djose/Temple - 4000 gil (Chest)": 4155,
    "Djose/Temple - Ether x1 (Chest)": 4157,
    "Djose/Temple - Remedy x1 (Chest)": 4158,
    "Djose/Temple - Mega Phoenix x1 (Chest)": 4159,
    "Djose/Temple - Cloister of Trials": 4580,
    "Djose/Temple - Ixion": 12298,
    "Djose/Temple - Switch Hitter (Chest)": 4156,
    "Djose/Pilgrimage Road - Halberd (NPC)": 4398,
    "Djose/Pilgrimage Road - Potion x10 (NPC)": 4399,
    "Djose/Pilgrimage Road - Hi-Potion x2 (NPC)": 4400,
    "Djose/Pilgrimage Road - Recruit Kyou": 28678,
    "Moonflow/South - Lv. 1 Key Sphere x3 (Shelinda Chest)": 4472,
    "Moonflow/South - X-Potion x1 (Chest)": 4293,
    "Moonflow/South - Lv. 1 Key Sphere x3 (Chest)": 4473,
    "Moonflow/South - Magic Def Sphere x1 (Chest)": 4474,
    "Moonflow/South - Phoenix Down x2 (Chest)": 4294,
    "Moonflow/South - 5000 gil (Chest)": 4295,
    "Moonflow/South - Extractor": 8204,
    "Moonflow/North - Al Bhed Primer XII": 24588,
    "Moonflow/North - Recruit Miyu": 28682,
    "Moonflow/North - Ether x1 (Chest)": 4296,
    "Moonflow/North - Rikku": 12294,
    "Moonflow/North - Antidote x4 (Chest)": 4297,
    "Moonflow/North - Mega-Potion x1 (Chest)": 4298,
    "Guadosalam/Guadosalam - Mega-Potion x1 (Chest)": 4161,
    "Guadosalam/Guadosalam - Al Bhed Primer XIII": 24589,
    "Guadosalam/Guadosalam - 3000 gil (Chest)": 4160,
    "Guadosalam/Guadosalam - Elixir x1 (Chest)": 4162,
    "Guadosalam/Guadosalam - Hi-Potion x2 (Chest)": 4163,
    "Guadosalam/Guadosalam - Recruit Yuma Guado": 28694,
    "Guadosalam/Farplane - Lightning Marble x8 (Chest)": 4314,
    "Guadosalam/Farplane - Brotherhood Upgrade": 24613,
    "Guadosalam/Farplane - Venus Crest (Chest)": 4368,
    "Thunder Plains/South - Phoenix Down x2 (Chest)": 4274,
    "Thunder Plains/South - Hi-Potion x2 (Chest)": 4275,
    "Thunder Plains/South - 5000 gil (Chest)": 4276,
    "Thunder Plains/South - Water Ball (Chest)": 4277,
    "Thunder Plains/Agency - Recruit Mifurey": 28681,
    "Thunder Plains/Agency - Al Bhed Primer XIV": 24590,
    "Thunder Plains/Agency - Yellow Shield (Ground Item)": 4441,
    "Thunder Plains/North - X-Potion x1 (Chest)": 4278,
    "Thunder Plains/North - Ether x1 (Chest)": 4279,
    "Thunder Plains/North - 2000 gil (Chest)": 4281,
    "Thunder Plains/North - Remedy x1 (Chest)": 4280,
    "Thunder Plains/South - Spirit Lance (Cactuar Statues)": 4284,
    "Thunder Plains/Agency - 5x Lightning Dodging": 4285,
    "Thunder Plains/Agency - 10x Lightning Dodging": 4286,
    "Thunder Plains/Agency - 20x Lightning Dodging": 4287,
    "Thunder Plains/Agency - 50x Lightning Dodging": 4288,
    "Thunder Plains/Agency - 100x Lightning Dodging": 4289,
    "Thunder Plains/Agency - 150x Lightning Dodging": 4290,
    "Thunder Plains/Agency - 200x Lightning Dodging": 4374,
    "Thunder Plains/Super Bosses - Dark Ixion": 8205,
    "Macalania/Woods - Sleepy Cait Sith (Chest)": 4165,
    "Macalania/Woods - 2000 gil (Chest)": 4164,
    "Macalania/Woods - Phoenix Down x3 (Chest)": 4166,
    "Macalania/Woods - Remedy x1 (Chest)": 4169,
    "Macalania/Woods - Al Bhed Primer XV": 24591,
    "Macalania/Woods - Spherimorph": 8206,
    "Macalania/Woods - Lucid Ring (Chest)": 4171,
    "Macalania/Lake Agency - Al Bhed Primer XVI": 24592,
    "Macalania/Lake Agency - Crawler": 8207,
    "Macalania/Lake Agency - 4000 gil (Chest)": 4172,
    "Macalania/Lake Road - Lv. 1 Key Sphere x1 (Chest)": 4173,
    "Macalania/Lake Road - Mega-Potion x1 (Chest)": 4174,
    "Macalania/Temple Road - 400 gil (Linna NPC)": 4401,
    "Macalania/Temple Road - Recruit Linna": 28679,
    "Macalania/Temple - Shell Targe (Tromell)": 4181,
    "Macalania/Temple - 5000 gil (Chest)": 4179,
    "Macalania/Temple - X-Potion x2 (Chest)": 4180,
    "Macalania/Temple - Remedy x2 (Chest)": 4183,
    "Macalania/Temple - Hi-Potion x2 (NPC)": 4404,
    "Macalania/Temple - Ether x1 (Man Sitting NPC)": 4403,
    "Macalania/Temple - Elixir x1 (Man Sitting NPC)": 4402,
    "Macalania/Temple - Phoenix Down x3 (Chest)": 4182,
    "Macalania/Temple - Seymour & Anima": 8208,
    "Macalania/Temple - Cloister of Trials": 4581,
    "Macalania/Temple - Chamber of the Fayth": 12299,
    "Macalania/Lake Agency - Wendigo": 8209,
    "Macalania/Lake Bottom - Lv. 2 Key Sphere (Chest)": 4176,
    "Macalania/Lake Bottom - Avenger (Chest)": 4175,
    "Macalania/Woods - Saturn Sigil (Butterfly Minigame)": 4373,
    "Macalania/Super Bosses - Dark Shiva": 8210,
    "Bikanel/Bikanel Oasis - Remedy x4 (Chest)": 4442,
    "Bikanel/Bikanel Oasis - Al Bhed Primer I": 24577,
    "Bikanel/Bikanel Oasis - Al Bhed Potion x8": 4306,
    "Bikanel/Bikanel Oasis - Al Bhed Primer III": 24579,
    "Bikanel/Bikanel East - Al Bhed Primer V": 24581,
    "Bikanel/Bikanel East - Ether x2 (Chest)": 4443,
    "Bikanel/Bikanel East - Al Bhed Potion x8": 4307,
    "Bikanel/Bikanel East - Al Bhed Primer XIV": 24590,
    "Bikanel/Bikanel East - Hi-Potion x4 (Chest)": 4444,
    "Bikanel/Bikanel Central - Hi-Potion x4 (Chest)": 4447,
    "Bikanel/Bikanel Central - X-Potion x2 (Chest)": 4446,
    "Bikanel/Bikanel Central - Mega-Potion x2 (Chest)": 4445,
    "Bikanel/Bikanel Central - Al Bhed Potion x8": 4308,
    "Bikanel/Bikanel Central - Al Bhed Primer XVIII": 24594,
    "Bikanel/Bikanel Central - Elixir x1 (Chest)": 4448,
    "Bikanel/Bikanel Central - Lv. 2 Key Sphere x1 (Chest)": 4450,
    "Bikanel/Bikanel Central - 10000 gil (Chest)": 4449,
    "Bikanel/Bikanel Central - Al Bhed Primer XVII": 24593,
    "Bikanel/Bikanel West - Megalixir x3 (Chest)": 4454,
    "Bikanel/Bikanel West - Teleport Sphere x2 (Chest)": 4455,
    "Bikanel/Bikanel West - Hi-Potion x8 (Chest)": 4451,
    "Bikanel/Bikanel West - Mercury Crest (Chest)": 4369,
    "Bikanel/Bikanel West - Mega-Potion x3 (Chest)": 4452,
    "Bikanel/Bikanel West - X-Potion x2 (Chest)": 4453,
    "Bikanel/Bikanel West - Mercury Sigil (Cactuar Village)": 4375,
    "Bikanel/Super Bosses - Dark Ifrit": 8211,
    "Home/Home - Hi-Potion x2 (NPC on Ground)": 4463,
    "Home/Home - Al Bhed Primer XIX": 24595,
    "Home/Home - Al Bhed Potion x6 (Chest)": 4456,
    "Home/Home - Al Bhed Primer XXI": 24597,
    "Home/Home - Special Sphere x1 (Al Bhed Password Chest)": 4492,
    "Home/Home - Skill Sphere x1 (Al Bhed Quiz Chest)": 4491,
    "Home/Home - Al Bhed Potion x4 (Chest)": 4457,
    "Home/Home - Al Bhed Primer XX": 24596,
    "Home/Home - Friend Sphere x1 (Al Bhed Vocabulary Chest)": 4493,
    "Home/Home - Area Completion - Lv. 2 Key Sphere x1": 4458,
    "Home/Home - Area Completion - Lv. 4 Key Sphere x4": 4459,
    "Home/Home - Area Completion - 10000 gil": 4460,
    "Airship/Bridge - Recruit Brother": 28674,
    "Airship/Bridge - Recruit Wakka": 28692,
    "Airship/Corridor - Recruit Rin": 28685,
    "Airship/Corridor - Complete Al Bhed Primers": 4501,
    "Airship/Cabin - Al Bhed Potion x4 (NPC)": 4471,
    "Airship/Roof - Evrae": 8212,
    "Airship/Roof - Sin Left Fin": 8213,
    "Airship/Roof - Sin Right Fin": 8214,
    "Airship/Roof - Sinspawn Genais and Core": 8215,
    "Airship/Roof - Overdrive Sin": 8216,
    "Bevelle/Temple - Al Bhed Primer XXII": 24598,
    "Bevelle/Temple - Cloister of Trials - Knight Lance": 4198,
    "Bevelle/Temple - Cloister of Trials - Destruction Sphere": 4313,
    "Bevelle/Temple - Cloister of Trials - Bahamut": 12300,
    "Bevelle/Via Purifico - Mega-Potion x1 (Chest)": 4206,
    "Bevelle/Via Purifico - Wht Magic Sphere x1 (Chest)": 4201,
    "Bevelle/Via Purifico - Elixir x1 (Chest)": 4200,
    "Bevelle/Via Purifico - Blk Magic Sphere x1 (Chest)": 4205,
    "Bevelle/Via Purifico - Skill Sphere x1 (Chest)": 4202,
    "Bevelle/Via Purifico - 10000 gil (Chest)": 4203,
    "Bevelle/Via Purifico - Lucid Ring (Chest)": 4204,
    "Bevelle/Via Purifico - Isaaru": 8218,
    "Bevelle/Underwater - Evrae Altana": 8219,
    "Bevelle/Underwater - Rematch (Chest)": 4197,
    "Bevelle/Underwater - Avenger (Chest)": 4196,
    "Bevelle/Highbridge - Seymour Natus": 8220,
    "Calm Lands/Plains - 5000 gil (Chest)": 4212,
    "Calm Lands/Plains - 10000 gil (Chest)": 4211,
    "Calm Lands/Plains - Lv. 2 Key Sphere x1 (Chest)": 4213,
    "Calm Lands/Plains - Al Bhed Primer XXIII": 24599,
    "Calm Lands/Plains - Recruit Naida": 28683,
    "Calm Lands/Plains - Recruit Svanda": 28689,
    "Calm Lands/Plains - Defender X": 8221,
    "Calm Lands/Gorge - Recruit Durren": 28675,
    "Calm Lands/Gorge - Rusty Sword": 4214,
    "Calm Lands/Chocobo - Wobbly Chocobo Minigame (Event)": 4433,
    "Calm Lands/Chocobo - Dodger Chocobo Minigame (Event)": 4434,
    "Calm Lands/Chocobo - Hyper Dodger Chocobo Minigame (Event)": 4435,
    "Calm Lands/Chocobo - Catcher Chocobo Minigame (Event)": 4436,
    "Calm Lands/Chocobo - Sun Sigil (Chocobo Catcher 0:00)": 4370,
    "Calm Lands/Plains - Caladbolg": 4210,
    "Remiem Temple/Al Bhed Primer XXIV": 24600,
    "Remiem Temple/Cloudy Mirror (Chocobo Race)": 4272,
    "Remiem Temple/Belgemine - Valefor Fight": 4475,
    "Remiem Temple/Belgemine - Ifrit Fight": 4477,
    "Remiem Temple/Belgemine - Ixion Fight": 4479,
    "Remiem Temple/Belgemine - Shiva Fight": 4481,
    "Remiem Temple/Belgemine - Bahamut Fight": 4430,
    "Remiem Temple/Belgemine - Yojimbo Fight": 4484,
    "Remiem Temple/Belgemine - Anima Fight": 4486,
    "Remiem Temple/Belgemine - Magus Sisters Fight": 4488,
    "Remiem Temple/Belgemine - Moon Sigil (Send Belgemine)": 4371,
    "Remiem Temple/Magus Sisters": 12303,
    "Monster Arena - Rewards/Nirvana": 4209,
    "Monster Arena - Rewards/Area Conquest - Besaid": 4520,
    "Monster Arena - Rewards/Area Conquest - Kilika": 4521,
    "Monster Arena - Rewards/Area Conquest - Miihen Highroad": 4522,
    "Monster Arena - Rewards/Area Conquest - Mushroom Rock Road": 4523,
    "Monster Arena - Rewards/Area Conquest - Djose Road": 4524,
    "Monster Arena - Rewards/Area Conquest - Thunder Plains": 4525,
    "Monster Arena - Rewards/Area Conquest - Macalania": 4526,
    "Monster Arena - Rewards/Area Conquest - Bikanel": 4527,
    "Monster Arena - Rewards/Area Conquest - Calm Lands": 4528,
    "Monster Arena - Rewards/Area Conquest - Stolen Fayth Cavern": 4529,
    "Monster Arena - Rewards/Area Conquest - Mt. Gagazet": 4530,
    "Monster Arena - Rewards/Area Conquest - Inside Sin": 4531,
    "Monster Arena - Rewards/Area Conquest - Omega Dungeon": 4532,
    "Monster Arena - Rewards/Species Conquest - Wolf (3x)": 4533,
    "Monster Arena - Rewards/Species Conquest - Reptile (3x)": 4534,
    "Monster Arena - Rewards/Species Conquest - Bird (5x)": 4535,
    "Monster Arena - Rewards/Species Conquest - Wasp (4x)": 4536,
    "Monster Arena - Rewards/Species Conquest - Imp (4x)": 4537,
    "Monster Arena - Rewards/Species Conquest - Eye (4x)": 4538,
    "Monster Arena - Rewards/Species Conquest - Flan (3x)": 4539,
    "Monster Arena - Rewards/Species Conquest - Element (3x)": 4540,
    "Monster Arena - Rewards/Species Conquest - Helm (3x)": 4541,
    "Monster Arena - Rewards/Species Conquest - Drake (4x)": 4542,
    "Monster Arena - Rewards/Species Conquest - Fungus (5x)": 4543,
    "Monster Arena - Rewards/Species Conquest - Bomb (5x)": 4544,
    "Monster Arena - Rewards/Species Conquest - Ruminant (5x)": 4545,
    "Monster Arena - Rewards/Species Conquest - Iron Giant (10x)": 4546,
    "Monster Arena - Rewards/Original Creation - Area Conquest x2": 4547,
    "Monster Arena - Rewards/Original Creation - Species Conquest x2": 4548,
    "Monster Arena - Rewards/Original Creation - Area Conquest x6": 4549,
    "Monster Arena - Rewards/Original Creation - Species Conquest x6": 4550,
    "Monster Arena - Rewards/Original Creation - All Fiends x1": 4551,
    "Monster Arena - Rewards/Original Creation - All Fiends x5": 4552,
    "Monster Arena - Rewards/Original Creation - Underwater Fiends in Mt. Gagazet x2": 4553,
    "Monster Arena - Rewards/Original Creation - All Fiends x10": 4554,
    "Monster Arena - Bosses/Arena Conquest - Stratoavis": 8241,
    "Monster Arena - Bosses/Arena Conquest - Malboro Menace": 8242,
    "Monster Arena - Bosses/Arena Conquest - Kottos": 8243,
    "Monster Arena - Bosses/Arena Conquest - Coeurlregina": 8244,
    "Monster Arena - Bosses/Arena Conquest - Jormungand": 8245,
    "Monster Arena - Bosses/Arena Conquest - Cactuar King": 8246,
    "Monster Arena - Bosses/Arena Conquest - Espada": 8247,
    "Monster Arena - Bosses/Arena Conquest - Abyss Worm": 8248,
    "Monster Arena - Bosses/Arena Conquest - Chimerageist": 8249,
    "Monster Arena - Bosses/Arena Conquest - Don Tonberry": 8250,
    "Monster Arena - Bosses/Arena Conquest - Catoblepas": 8251,
    "Monster Arena - Bosses/Arena Conquest - Abaddon": 8252,
    "Monster Arena - Bosses/Arena Conquest - Vorban": 8253,
    "Monster Arena - Bosses/Species Conquest - Fenrir": 8254,
    "Monster Arena - Bosses/Species Conquest - Ornitholestes": 8255,
    "Monster Arena - Bosses/Species Conquest - Pteryx": 8256,
    "Monster Arena - Bosses/Species Conquest - Hornet": 8257,
    "Monster Arena - Bosses/Species Conquest - Vidatu": 8258,
    "Monster Arena - Bosses/Species Conquest - One-Eye": 8259,
    "Monster Arena - Bosses/Species Conquest - Jumbo Flan": 8260,
    "Monster Arena - Bosses/Species Conquest - Nega Elemental": 8261,
    "Monster Arena - Bosses/Species Conquest - Tanket": 8262,
    "Monster Arena - Bosses/Species Conquest - Fafnir": 8263,
    "Monster Arena - Bosses/Species Conquest - Sleep Sprout": 8264,
    "Monster Arena - Bosses/Species Conquest - Bomb King": 8265,
    "Monster Arena - Bosses/Species Conquest - Juggernaut": 8266,
    "Monster Arena - Bosses/Species Conquest - Ironclad": 8267,
    "Monster Arena - Bosses/Original Creation - Earth Eater": 8268,
    "Monster Arena - Bosses/Original Creation - Greater Sphere": 8269,
    "Monster Arena - Bosses/Original Creation - Catastrophe": 8270,
    "Monster Arena - Bosses/Original Creation - Th'uban": 8271,
    "Monster Arena - Bosses/Original Creation - Neslug": 8272,
    "Monster Arena - Bosses/Original Creation - Ultima Buster": 8273,
    "Monster Arena - Bosses/Original Creation - Shinryu": 8274,
    "Monster Arena - Bosses/Original Creation - Nemesis": 8275,
    "Cavern of the Stolen Fayth/Megalixir x1 (Chest)": 4216,
    "Cavern of the Stolen Fayth/Lv. 2 Key Sphere x1 (Chest)": 4217,
    "Cavern of the Stolen Fayth/Fortune Sphere x1 (Chest)": 4218,
    "Cavern of the Stolen Fayth/Mega-Potion x1 (Chest)": 4219,
    "Cavern of the Stolen Fayth/Al Bhed Primer XXV": 24601,
    "Cavern of the Stolen Fayth/Flexible Arm (Chest)": 4220,
    "Cavern of the Stolen Fayth/MP Sphere x1 (Chest)": 4221,
    "Cavern of the Stolen Fayth/X-Potion x2 (Chest)": 4222,
    "Cavern of the Stolen Fayth/Yojimbo": 12302,
    "Cavern of the Stolen Fayth/Super Bosses - Dark Yojimbo": 8223,
    "Mt. Gagazet/Outside - Biran and Yenke": 8224,
    "Mt. Gagazet/Outside - 20000 gil (Chest)": 4224,
    "Mt. Gagazet/Outside - Mega-Potion x2 (Chest)": 4225,
    "Mt. Gagazet/Outside - Defending Bracer (Chest)": 4226,
    "Mt. Gagazet/Outside - Lv. 4 Key Sphere x1 (Chest)": 4227,
    "Mt. Gagazet/Outside - HP Sphere x1 (Chest)": 4228,
    "Mt. Gagazet/Outside - Seymour Flux": 8225,
    "Mt. Gagazet/Outside - Saturn Crest (Chest)": 4366,
    "Mt. Gagazet/Inside - Lv. 1 Key Sphere x1 (Chest)": 4232,
    "Mt. Gagazet/Inside - Fortune Sphere x1 (Chest)": 4233,
    "Mt. Gagazet/Inside - Return Sphere x1 (Chest)": 4234,
    "Mt. Gagazet/Inside - Recovery Ring (Chest)": 4235,
    "Mt. Gagazet/Inside - Pep Talk (Chest)": 4231,
    "Mt. Gagazet/Inside - Sanctuary Keeper": 8227,
    "Mt. Gagazet/Super Bosses - Dark Anima": 8226,
    "Zanarkand/Overpass - Fortune Sphere x1 (Chest)": 4241,
    "Zanarkand/Overpass - Spiritual Targe (Chest)": 4242,
    "Zanarkand/Dome - 10000 gil (Chest)": 4243,
    "Zanarkand/Dome - Friend Sphere x1 (Chest)": 4244,
    "Zanarkand/Dome - Lv. 3 Key Sphere x1 (Chest)": 4245,
    "Zanarkand/Dome - Luck Sphere x1 (Chest)": 4246,
    "Zanarkand/Temple - Spectral Keeper": 8228,
    "Zanarkand/Temple - Yunalesca": 8229,
    "Zanarkand/Temple - Sun Crest (Chest)": 4363,
    "Zanarkand/Temple - Cloister of Trials ": 4305,
    "Zanarkand/Super Bosses - Dark Bahamut": 8230,
    "Inside Sin/Sea of Sorrow - Phantom Ring (Chest)": 4262,
    "Inside Sin/Sea of Sorrow - Special Sphere x1 (Chest)": 4263,
    "Inside Sin/Sea of Sorrow - Elixir x1 (Chest)": 4259,
    "Inside Sin/Sea of Sorrow - Wizard Lance (Chest)": 4260,
    "Inside Sin/Sea of Sorrow - Lv. 3 Key Sphere x1 (Chest)": 4261,
    "Inside Sin/Sea of Sorrow - Seymour Omnis": 8231,
    "Inside Sin/City of Dying Dreams - Lv. 4 Key Sphere x1 (Chest)": 4264,
    "Inside Sin/City of Dying Dreams - Four-on-One (Chest)": 4265,
    "Inside Sin/City of Dying Dreams - Defending Bracer (Chest)": 4266,
    "Inside Sin/City of Dying Dreams - 20000 gil (Chest)": 4267,
    "Inside Sin/City of Dying Dreams - Megalixir x1 (Chest)": 4270,
    "Inside Sin/City of Dying Dreams - HP Sphere x1 (Chest)": 4268,
    "Inside Sin/City of Dying Dreams - Defense Sphere x1 (Chest)": 4269,
    "Inside Sin/City of Dying Dreams - Laevatein (Chest)": 4271,
    "Omega Ruins/Teleport Sphere x1 (Chest)": 4426,
    "Omega Ruins/Al Bhed Primer XXVI": 24602,
    "Omega Ruins/Ultima Weapon": 8235,
    "Omega Ruins/Friend Sphere x1 (Chest)": 4427,
    "Omega Ruins/Omega Weapon": 8236,
    "Omega Ruins/Magic Sphere x1 (Chest)": 4428
}

tracker_world = {
        "map_page_maps": ["maps/maps.json"],
        "map_page_locations": [
            "locations/Airship.json",
            "locations/Al Bhed Primers.json",
            "locations/Al Bhed Ship.json",
            "locations/Baaj Temple.json",
            "locations/Besaid.json",
            "locations/Bevelle.json",
            "locations/Bikanel.json",
            "locations/Blitzball Recruits.json",
            "locations/Calm Lands.json",
            "locations/Cavern of the Stolen Fayth.json",
            "locations/Celestial.json",
            "locations/Djose.json",
            "locations/Guadosalam.json",
            "locations/Inside Sin.json",
            "locations/Kilika.json",
            "locations/Luca.json",
            "locations/Macalania.json",
            "locations/Miihen Highroad.json",
            "locations/Monster Arena.json",
            "locations/Moonflow.json",
            "locations/Mt. Gagazet.json",
            "locations/Mushroom Rock Road.json",
            "locations/Omega Ruins.json",
            "locations/Overdrives.json",
            "locations/Party Member.json",
            "locations/Remiem Temple.json",
            "locations/S.S. Liki.json",
            "locations/S.S. Winno.json",
            "locations/Spira.json",
            "locations/Super Bosses.json",
            "locations/Thunder Plains.json",
            "locations/Zanarkand.json",
        ],
        "map_page_layouts": ["layouts/maps.json"],
        "map_page_setting_key": "Slot:{player}:FFX_ROOM",
        "map_page_index": map_page_index,
        "external_pack_key": "ut_poptracker_path",
        "poptracker_name_mapping": poptracker_name_mapping
    }



